### ISSUE TITLE
vpn: check vtun availabilty

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#100]
client tries to connect to a non-existing vtun server, if server is pingable, but no vtun is runnig

**Comment by bittorf** [comment]
nc -w 3 -z 4.vpn.weimarnetz.de && echo 'ja geht'

**Comment by glycoknob** [comment]
```
[ $(echo "test" | nc -w 3 3.v.weimarnetz.de 5001 | grep -c VTUN) -gt 0 ] \
   && echo "läuft" ||  echo "kaputt"
```

bei der Gelegenheit könnte man auch einbauen, die Liste der Server durchzugehen wenn der mit dem schnellsten Ping nicht läuft... dafür müsste das `persist yes` auf der `vtund.conf` weg. 

Beim heutigen Disconnect-Bug würde obiger Check auch nicht helfen, aber wenn alle Server durchprobiert würden, dann ist die Chance höher das einer läuft... 

Mal sehen
