### ISSUE TITLE
FSG ojemine

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#101]
Bilder von Basti: http://intercity-vpn.de/files/weimarnetz/fsg/

Skizze, delegiert zu Basti

Anschreiben, macht Andi
Stadtratsbeschluss... inkl Skizze, Terminbitte (Aufmass Detailplanung)
Terminvorschlag 30.6. ab 1200 oder 8./9.7 ab 1200

Elektriker: Wanddurchbruch ins "Häuschen", Gehäuse für Technik innen?

Masthalterungen Nanostations - was haltet ihr davon: http://www.amazon.com/Ubiquiti-Networks-Nanostation-Mount-NANOMOUNT/dp/B00HXT8IW8
Patchkabel von der Rolle
Crimpzeugs
Verlegerohr 

POE Ports: 14 vorhanden von 16 (Switch untereinander verbunden)

2 x 2,4 ghz lokal 
4 x 2,4 ghz Richtfunk
4 x 5ghz Richtfunk
alles nanostations

**Comment by glycoknob** [comment]
FSG erstmal auf Eis oder?
