### ISSUE TITLE
Question: how to set vtun port on servers?

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#102]
it is set here: https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-addons/etc/kalua/vpn#L68
is it possible to fake uci files on non-openwrt systems?

**Comment by bittorf** [comment]
very simple:
echo >>'/etc/kalua_uci' 'system.vpn.port=5001'

after that on a server:
root@server1:~# . /tmp/loader
root@server1:~# uci get system.vpn.port
5001
