### ISSUE TITLE
VPN: Kein Internet für Nachbarn, wenn der VPN-Tunnel nicht steht

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#106]

**Comment by storchi** [comment]
wasn das fuer deutsch?
cs

**Comment by andibraeu** [comment]
Welcher Deutsch?

**Comment by storchi** [comment]
dem

**Comment by bittorf** [comment]
d.h. es soll kein internet angekündigt (HNA4) werden?

**Comment by storchi** [comment]
nein, laut andi ist das bei ihm so
also ein bug

**Comment by bittorf** [comment]
bitte mal bei einem einspeiser mit aktueller firmware diese ausgabe senden:

ip rule show

**Comment by andibraeu** [comment]
scheint ein problem bei mir zu hause zu sein, Problem konnte im MR nicht nachgestellt werden
