### ISSUE TITLE
Splashpage: Update-check führt zu Hänger, wenn Seite nicht erreichbar

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#108]
LUCI hat kein Timeout-Parameter

**Comment by bittorf** [comment]
für solche sachen besser _wget() verwenden, genau aus diesem grund.

**Comment by 0x6d54** [comment]
lua Script nochmal checken https://github.com/weimarnetz/openwrt-packages/commit/7061faedc47de800d1902989f8006e3bb55dc35e

**Comment by andibraeu** [comment]
ist jetzt erledigt
