### ISSUE TITLE
UDP für VPN evaluieren

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#114]
Aus der `vtund.conf`: 

       proto tcp|udp
              protocol to use.  By default, vtund(8) will use TCP protocol.  UDP is recommended for
              ether and tun tunnels only.  This option is ignored by the client.

Wäre also ein Switch am Server...  bzw. bräuchten wir vtun-3.0.3 und müssten (eventuell) noch das hier beim Server setzen.

    nat_hack client|server|no
              side  to  use  nat_hack on.  By default, vtund(8) uses a 'no' setting.  The side that
              the NAT hack is enabled on will perform a delayed UDP socket connect. Should only  be
              enabled  for  the side outside of the NAT (typically the server)! Setting 'client' on
              the server or 'server' on the client is ignored, as to make  a  single  configuration
              file reusable on both sides.

              This  is  only relevant if you use proto udp. The NAT hack delays the UDP socket con‐
              nect until the first UDP packet is received from the other side of  the  tunnel.  The
              socket is then connected to the actual source port of the packet (on the NAT box) and
              not to the one indicated in the handshake (which is behind NAT and probably  unreach‐
              able).   The  first  echo  request  is  also  disabled  on the side with the NAT hack
              enabled.

              Currently the mechanism works only for one side, for a single NAT traversal.  If  you
              enable it for both sides, both will wait for a first packet and the tunnel will never
              transport any data.

              Security warning! Due to the nature of the delayed  connection,  the  tunnel  can  be
              hijacked  in  theory by an attacker behind the same NAT, sending the first UDP packet
              to the server UDP port, before the real client does. If you  do  not  understand  the
              risks,  or  want  to remain as secure as possible behind this kind of NAT router, use
              proto tcp as a NAT traversal solution.

              Because of the security issue mentioned above, this option might be  disabled  during
              compilation (configure --disable-nathack).

Ich würd es mal testen ob es besser läuft

**Comment by andibraeu** [comment]
läuft ja bereits
