### ISSUE TITLE
implement vpn only, no internet via vpn

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#124]

**Comment by bittorf** [comment]
also im prinzip: kein traffic durch den tunnel leiten, aber kontakt zur wolke halten oder wie?

**Comment by glycoknob** [comment]
genau - das müsste nur die eine `ip rule` im vpn script sein.

**Comment by andibraeu** [comment]
richtig, die ip rule wird einfach nicht gesetzt

**Comment by bittorf** [comment]
oh, besser extra variable einfuehren - vorschlag/bir mir heisst die:

system.@vpn[0].hideandseek_disabled

und ist bool.

**Comment by andibraeu** [comment]
gelöst in #151
