### ISSUE TITLE
Chaos Calmer Release Party planen

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#125]

**Comment by andibraeu** [comment]
@storchi Schnaps koofn

1 1/2 oz Plymouth® gin
1/4 oz triple sec
1 1/2 oz orange juice
3/4 oz lime juice
1 tsp grenadine syrup

**Comment by bittorf** [comment]
29. September oder 6. Oktober?

**Comment by andibraeu** [comment]
wenn die firmware fertig ist

**Comment by andibraeu** [comment]
5.1.2016 oder 12.1.2016?

**Comment by storchi** [comment]
Am 07.12.2015 um 12:20 schrieb Andi Bräu:
> 5.1.2016 oder 12.1.2016?

ich kann immer

**Comment by storchi** [comment]
Am 22.09.2015 um 23:22 schrieb Andi Bräu:
> @storchi <https://github.com/storchi> Schnaps koofn
>
> 1 1/2 oz Plymouth® gin
> 1/4 oz triple sec
> 1 1/2 oz orange juice
> 3/4 oz lime juice
> 1 tsp grenadine syrup

check

**Comment by bittorf** [comment]
ich schlage Dienstag den 12. Januar vor...

**Comment by andibraeu** [comment]
* S140 gebucht
* Grill gebucht
* Thomas macht c64-Musik
* Barschichten
* Einladungen verschickt

**Comment by andibraeu** [comment]
TODOs:

* Getränke für Cocktail im Cafe bestellen (Klaus)
* Grillgut kaufen
* Spendenbox

**Comment by andibraeu** [comment]
die is fertig. Abrechnung muss noch gemacht werden

**Comment by glycoknob** [comment]
War Super! Danke euch nochmal für die Orga! Ich war ja nur zum trinken da ;)
