### ISSUE TITLE
splashpage iphone6 <-> 37711 

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#144]
ein Benutzer berichtet, dass die splashpage auf dem iphone6 nicht kommt.
kann das wer nachprüfen?
andere Endgeräte gehen.
cs

**Comment by bittorf** [comment]
mit version stable = r36817 und r37890

**Comment by storchi** [comment]
das sind ja total krumme versionen - wer macht denn sowas?
mit 37711 wäre das nicht passiert

**Comment by bittorf** [comment]
schwer zu sagen...bin gerade unsicher wer damals die VHS geraete vorbereitet hat.

**Comment by andibraeu** [comment]
mit iphone 6 und ios9 hab ich keine Probleme mit den Splashpages, getestet am Mon Ami, Musikschule, Maschinenraum, zu Hause

**Comment by bittorf** [comment]
kann es sein, das es mit gestörtem VPN zusammenhing?

**Comment by storchi** [comment]
laut wuschel gingen andere geräte an den betreffenden mon ami knoten.

**Comment by storchi** [comment]
weitere aussage megadave: aktuellstes iphone 6plus mit AA-37711 geht!

**Comment by bittorf** [comment]
arrrg. evtl. muessen wir es an einer iOS-version festzurren - ich frage mal wuschel.
es gibt halt im alten ath9k ein paar fiese bugs, die mit dem stromsparmodus / timing
von iPhones nicht klar kommen. ich befuerchte das es sowas ist (und das tritt dann
auch nicht immer auch...)

**Comment by storchi** [comment]
laut wuschel tritt es immer auf. diese ominösen fiesen bugs können es auch nicht sein, da das iphone von wuschel wlan und ip mässig verbunden ist. meiner meinung nach, haben die doofen 6er iphones eh alle die gleiche ios version. 
lass es dir mal vorführen, basti.
cs

**Comment by storchi** [comment]
so, ganze aufregung umsonst.
ein neustart vom iphone hat den "fehler" behoben.
mannmannmann

**Comment by kaese77** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Da griegsch ´nen iFön!


> so, ganze aufregung umsonst. ein neustart vom iphone hat den "fehler" behoben. mannmannmann
> 
> — Reply to this email directly or view it on GitHub <https://github.com/weimarnetz/weimarnetz/issues/144#issuecomment-157010154>.
> 

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJWSclpAAoJEJuS/5F7Le+BMhMH/RwYranNNkEZu5Ez5wCrQN/H
ioqPeuWIXOkB+OKWKAXeYveTtSElNJieiZc7FSvprqwyyrnJFWBTOvQo0eSxqrHX
m4ZC0ZXWE7GwGzTZ/LzKF5TyofP+ykCHRDJuiOkbX2V2daUqlFURCPyvt28h8nEd
XB/PrJvGrWBJW5DmIWY/Y7tXV0vg3FC3gjaMJHtie8WeMAbjCpJLK0D0EqDCO+r5
QC29NtjQovfl6m3FSbpF0BeWx/Mtkh/mgHCDDo/tWdkZFvC0ItymwlnMNEyi/ulH
KbCHaGNCJ9WCBfv2jlPcWbwoFvDbNx+rLjxHitgXPpE/9Jirlx7gGWk8MPu9rXg=
=K3cY
-----END PGP SIGNATURE-----
