### ISSUE TITLE
CC: Luci schickt manchmal keine Auth-Cookies mit

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#148]
Super seltsamer Bug auf dem s140 Router: Einloggen klappt, aber weitere Aktionen fragen immer erneut nach einem Passwort - Ursache ist, dass kein Session-Cookie erzeugt wird oder mitgeschickt wird (mit Netzwerk-Tools vom Browser getestet).... 

Nach einen Reboot? durch ein watch-Script läuft es wieder

Flash voll? Direkt nach reboot waren etwa 140k frei - jetzt etwa 188k: 

```
root@s140:~ df -h 
Filesystem                Size      Used Available Use% Mounted on
rootfs                  448.0K    260.0K    188.0K  58% /
/dev/root                 3.0M      3.0M         0 100% /rom
tmpfs                    14.3M      1.2M     13.1M   8% /tmp
/dev/mtdblock3          448.0K    260.0K    188.0K  58% /overlay
overlayfs:/overlay      448.0K    260.0K    188.0K  58% /
tmpfs                   512.0K      4.0K    508.0K   1% /dev
``` 

Speicher Voll? Ich glaub ich hab ein Memory-Leak ins VPN-Script eingebaut (Sorry) - kommt in anderes Ticket / Pull-Request - aber warum deshalb keine Cookies? 

In Luci gibt es ein Ticket, evtl wurde rpcd wegen Speichermangel gekillt? 
https://github.com/openwrt/luci/issues/547 

Hängt vielleicht mit dem Bad Gateway Bug zusammen... https://github.com/weimarnetz/weimarnetz/issues/146

**Comment by glycoknob** [comment]
Memory Leak ist hier gefixt: https://github.com/weimarnetz/weimarnetz/pull/149

**Comment by bittorf** [comment]
rpcd wird fuer die cookies nicht gebraucht, das macht uhttpd selbst.
ist es weg wenn der speichermangel weg ist?

**Comment by glycoknob** [comment]
rpcd wurde in luci genau dafür eingebaut, wenn ich den commit richtig stehe: https://github.com/openwrt/luci/commit/199c8cbc4c32506ecfe89850615b88a3f0276dd3 

Ist relativ neu, aber wohl in CC und Trunk einthalten. 

Ansonsten hab ich keine Ahnung wo das Problem sein könnte... gut möglich, dass es ein gekillter rpcd war, aber wirklich sicher bin ich mir nicht.

**Comment by bittorf** [comment]
ok, fuer luci hast du recht. das normale basic.auth macht der uhttpd selbst. insofern kann es mit einem gekillten rpcd zusammenhaengen. warum wird der nicht durch procd neugezuendet?

**Comment by glycoknob** [comment]
Hmm, für rpcd fehlt die `respawn` Zeile im Init-Script, weiß nicht wie OpenWRT das handhabt, die scheint generell nur selten angegeben zu sein. Siehe hier: https://dev.openwrt.org/browser/trunk/package/system/rpcd/files/rpcd.init

**Comment by glycoknob** [comment]
```
# respawn automatically if something died, be careful if you have an alternative process supervisor
  # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
```

**Comment by bittorf** [comment]
diese elenden idioten und nichtkönner...

**Comment by andibraeu** [comment]
können wir hier noch etwas tun? Ist das nochmal aufgetreten?

**Comment by glycoknob** [comment]
Können das Init-Script für rpcd patchen, so dass respawn aktiv ist und rpcd ggf. neugestartet wird... allerdings rebooted sich der Router bei OOM (Prozess wird wegen zu wenig RAM gekillt) sowieso neu, aber vielleicht war OOM auch nicht das Problem.

**Comment by bittorf** [comment]
bei speichermangel muss nicht zwangslaeufig ein OOM auftreten. es kann auch sein, das dies im programm abgefangen wird, aber ein buggy codepfad fuehrt zu einem prozesskill/SIGSEGV (oder so).
die rpcd-init zu patchen fuer respawn waere sinnvoll.

**Comment by glycoknob** [comment]
done: https://github.com/weimarnetz/builder/commit/e76689599289db73082cddef01ed56647f42a3fc

**Comment by glycoknob** [comment]
das hat nicht geklappt. das hier klappt: https://github.com/weimarnetz/builder/commit/cba347fc40d5ffb2febf613a0b681e3b7f066f6f - ich schließ das mal, sollte jetzt klappen.

**Comment by glycoknob** [comment]
läuft: 

```
root@netbox:~ pidof rpcd
1101
root@netbox:~ kill 1101
root@netbox:~ pidof rpcd
root@netbox:~ pidof rpcd
root@netbox:~ pidof rpcd
root@netbox:~ pidof rpcd
5577
root@netbox:~ pidof rpcd
5577
```
