### ISSUE TITLE
Keypair für Signed Packages erzeugen

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#150]
Hintergrund: Packages sind signiert und mit opkg update kann man nur Pakete mit der richtigen Signatur installieren/updaten. Standardmäßig wird diese Signatur beim Bauen neu erzeugt und ist im OpenWRT-Verzeichnis in key-build und key-build.pub abgelegt.

Für unsere offiziellen Releases müssen wir dann alles einmal mit dem offiziellen Schlüsselpaar bauen.

**Comment by bittorf** [comment]
dazu gehört auch gleich als erinnerung, das wir das Pärchen sichern um es im Fehlerfall wieder herstellen zu können.

**Comment by andibraeu** [comment]
hab dafür mal ein private repository hier beantragt...

**Comment by andibraeu** [comment]
Keys werde ich in unser privates repo packen: https://github.com/weimarnetz/keys
