### ISSUE TITLE
GM: splashpage fordert zum Downgrade

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#157]
ich finds ja gut!
![bildschirmfoto vom 2015-11-20 09 53 24](https://cloud.githubusercontent.com/assets/1206720/11296798/9401a6ec-8f74-11e5-96d7-8e01b39530de.png)

**Comment by glycoknob** [comment]
Hier ist der Code: 

https://github.com/weimarnetz/openwrt-packages/blob/master/utils/luci-weimar-splash/luasrc/view/weimarnetz-splash/infopage.htm#L79

In dem Fall ist es so, dass es mit ODER verknüpft ist... also OpenWRT ist neuer ODER kalua - hier ist kalua neuer...

**Comment by glycoknob** [comment]
Ich glaub aber, dass das so grad eher verwirrt als hilft - oder?

**Comment by andibraeu** [comment]
Ja, das liegt an der falschen Versionsnummer für kalua. Ist in Arbeit.

**Comment by andibraeu** [comment]
ist nun auch für den Bau als OpenWRT-Package gelöst: https://github.com/weimarnetz/openwrt-packages/commit/442629cf131e12665f281552bae1cf0f3845869e
