### ISSUE TITLE
VPN: Verbindung kommt nicht zu stande

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#163]
Beispiel: WeimarnetzMaschinenraum

lock ist gesetzt, und nichts passiert

**Comment by andibraeu** [comment]
_net local_inet_offer sagt, es handele sich um eine PPPoE-Verbindung, ist aber dhcp auf wan

@Bittorf sagt dir das was?

**Comment by bittorf** [comment]
interessant. ich pruefe.

**Comment by andibraeu** [comment]
doch, ist das allgemein bekannte standardpasswort...

Ausgabe _net local_inet_offer:
```
Nov 25 10:43:10 ' [up 23858s 4501504 bytes free] TERM:screen -ash [daemon.debug] net_local_inet_offer() PHYDEV: 'eth1' METRIC: '' N: 'static' D: '192.168.254.1'
Nov 25 10:43:10 ' [up 23858s 4468736 bytes free] TERM:screen -ash [daemon.info] net_local_inet_offer() found local default-gateway over device 'eth1' = 'pppoe'
```

**Comment by andibraeu** [comment]
hab da gerade mal wan eingetragen: https://github.com/weimarnetz/weimarnetz/blob/GebrannteMandeln/openwrt-addons/etc/kalua/net#L409

zusammen mit #165 startet vpn zumindest

**Comment by bittorf** [comment]
ok, komme nun drauf. ursache gefunden, bereite patch vor.

**Comment by bittorf** [comment]
ok, dies ist die ursache allen uebels:
https://github.com/weimarnetz/weimarnetz/pull/166
https://github.com/weimarnetz/weimarnetz/pull/167

die aenderung in vpn_needed() wuerde ich ja rueckgaengig machen, oder?

**Comment by andibraeu** [comment]
warum? ist ein return 0 nicht relativ eindeutig und lesbar?

**Comment by andibraeu** [comment]
mach den PR mal bitte in Gebrannte Mandeln

**Comment by bittorf** [comment]
du hast recht. das return 0 muss bleiben.
ich dacht PR167 ist in Gebrannte Mandeln?

**Comment by andibraeu** [comment]
nein, da wolltest du zurück in master mergen

**Comment by bittorf** [comment]
puh...ich versuchs nochmal

**Comment by andibraeu** [comment]
das funktioniert nun
