### ISSUE TITLE
_watch vpn findet server nicht in Nachbarsliste

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#170]
deshalb wird vpn immer wieder neu gezündet

An der Stelle:
https://github.com/weimarnetz/weimarnetz/blob/GebrannteMandeln/openwrt-addons/etc/kalua/watch#L95

**Comment by bittorf** [comment]
mach mal beim "grep -q" das 'q' weg und zeige den output. Der test sieht eigentlich OK aus.

**Comment by bittorf** [comment]
ok, problem verstanden. ich mach nen patch

**Comment by andibraeu** [comment]
funzt, danke!
