### ISSUE TITLE
Usability Weimarnetz Konfigurationsseite

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#174]
Bin grad am testen (läuft soweit prima!), aber eine Sache ist wirklich verwirrend: 

Wenn ich die VPN-Einstellungen will, dann muss ich erst ganz unten die Änderungen aktivieren und _dann_ erst auf den Knopf drücken... 

Siehe diesen hochgradig professionellen Screenshot: 

1. Ändert erst die UCI Einträge, 
2. nutzt ja diese

![ffweimar](https://cloud.githubusercontent.com/assets/187041/11431065/96e87bf8-9490-11e5-8e38-44aeb0e6b9c8.png)

Könnten wir die VPN-Änderungen da auch mit dem Apply erledigen? Dann wäre noch die Frage inwiefern die Splash UCI Variablen erst mit Reboot wirksam werden (ich glaube ja, sonst vielleicht nochmal _netfilter restart irgendwo einbauen) 

Dann bekomme ich nach einige Zeit des nichts tuns Gateway-Timeouts auf der Seite - bin mir nicht so sicher woran das liegt..  laut Chrome wird da ein POST gesendet.. ich weiß aber nicht wo der herkommt. 

ich teste mal weiter.

**Comment by andibraeu** [comment]
wenns einfach wär, hätte ich das da eingebaut :-) Man müsste glaub ich ein init-script bauen und könnte darüber dann vpn auch mit apply neu starten

**Comment by glycoknob** [comment]
okay, das neuladen macht wohl [luci-reload](https://github.com/openwrt/luci/blob/master/modules/luci-base/root/sbin/luci-reload) zusammen mit `/etc/config/ucitrack` - entweder ein init-script oder dieses exec was da steht... da müssten wir was bauen können. gibt wohl auch noch hooks, die man dafür nutzen könnte: https://github.com/elationfoundation/luci_tutorials/blob/master/04-model-cbi.md

**Comment by andibraeu** [comment]
hab mal an der richtigen Stelle ein Issue angelegt: https://github.com/weimarnetz/openwrt-packages/issues/21
