### ISSUE TITLE
Makefiles für /etc/profile.d/kalua.sh anpassen

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#175]
Die ganzen Shell-Goodies sind umgezogen - siehe hier: 
https://github.com/weimarnetz/weimarnetz/commit/68d07573d0329c9b6a55a1cd09ad9d5361d94986

Da fehlen noch die Einträge im Makefile hier: https://github.com/weimarnetz/openwrt-packages/blob/master/utils/kalua/Makefile

**Comment by bittorf** [comment]
gut gesehen!
