### ISSUE TITLE
Besseres Default Passwort

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#177]
die Aufforderung das Passwort zu wechseln sollte dennoch bleiben, aber damit könnten wir zumindest SSH-Bots oder vergessene Router mit Default-Passwort _etwas_ aus der ganz offensichtlichen Schusslinie nehmen - irgendwas leicht zu merkendendes, nicht zu kurzes fällt uns schon ein. 

Für 12 Zeichen muss jemand schon ein paar Tage die GPU brutzeln lassen, wenn es nur als Hash im Repository ist: http://blog.codinghorror.com/speed-hashing/ 

Sowas hier https://xkpasswd.net/s/ - 3 bis 4 leicht zu merkende Worte

**Comment by bittorf** [comment]
fuer bots wuerde "weimarnetz" reichen. jemand mit genug insiderwissen wuerde auch andere kennen, oder?

**Comment by andibraeu** [comment]
Man muss aber alle Funktionen anpassen, die auf das Standardpasswort hinweisen?

Ist vielleicht kein pw besser?

**Comment by bittorf** [comment]
ich denke auch, das dies unnoetig ist. die hinweise zum setzen reichen doch. wer das ignoriert will es nicht anders.

**Comment by glycoknob** [comment]
@bittorf: stimmt. Ist ja auch im Meshkit, wäre z.B: eine Idee.

**Comment by andibraeu** [comment]
kann das wieder zu?

**Comment by bittorf** [comment]
ich denke ja.
