### ISSUE TITLE
Release Branch auch für openwrt-packages Feed?

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#181]
macht es Sinn das auch für `openwrt-packages` zu machen? Müssten wir noch die feeds.conf vom Builder anpassen.

**Comment by andibraeu** [comment]
glaub, das ist nicht so sinnvoll. Man müsste eher die einzelnen Projekte auslagern wie es bei Kalua z.B. ist. Im OpenWRT-Packages-Feed legen wir ja die verwendete Version fest.
