### ISSUE TITLE
luci-theme-material evaluieren

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#184]
schönes neues Theme basierend auf http://www.getmdl.io/ 
https://github.com/LuttyYang/luci-theme-material

Ich teste mal wie viel Platz das frisst, würd das gerne per Default haben wollen!

**Comment by glycoknob** [comment]
```
-rw-r--r--  1 mt mt  14K Nov 27 18:16 luci-theme-bootstrap_git-15.330.80595-c123fa8-1_all.ipk
-rw-r--r--  1 mt mt  50K Nov 27 18:16 luci-theme-material_git-15.330.80595-c123fa8-1_all.ipk
``` 

Mal sehen ob sich das lohnt.

**Comment by glycoknob** [comment]
fazit nach 5 minuten: nope, nope, nope...

**Comment by andibraeu** [comment]
ganz schön groß... die haben da auch jquery eingebaut...

**Comment by andibraeu** [comment]
ist das im luci-feed drin? man könnte es als optionales paket bauen und anbieten

**Comment by glycoknob** [comment]
ist zumindest im trunk, aber ist momentan noch mehr kaputt als sinnvoll.
