### ISSUE TITLE
/usr/lib/lua/luci/controller/weimarnetz/splash.lua: bad header in precompiled chunk

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#186]
Ebenfalls nach sysupgrade - und build mit `./build_release.sh meta.ffweimar-4MBtrunk`

Auf x86 läufts.. kann das jemand reproduzieren? 

```
/usr/lib/lua/luci/ccache.lua:70: error loading module 'luci.controller.weimarnetz.splash' from file '/usr/lib/lua/luci/controller/weimarnetz/splash.lua':
	/usr/lib/lua/luci/controller/weimarnetz/splash.lua: bad header in precompiled chunk
stack traceback:
	[C]: in function 'loader'
	/usr/lib/lua/luci/ccache.lua:70: in function </usr/lib/lua/luci/ccache.lua:61>
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:509: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:536: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:216: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>
```

**Comment by andibraeu** [comment]
Meine Beobachtung bisher: in den Minuten nach dem flashen kommt das vor, danach nicht mehr. 

Geht der der Fehler bei dir irgendwann weg?

**Comment by glycoknob** [comment]
Ging jetzt nicht weg - zumindest nicht in 20-30m - ersetze ich die kompilierte Datei durch den Source, dann klappt es.

Ich glaube die make-Zeile hier könnte man rausnehmen, dann wird nicht kompiliert? 
 https://github.com/weimarnetz/openwrt-packages/blob/master/utils/luci-weimar-splash/Makefile#L31 

Ist vielleicht auch ein Bug in trunk..

**Comment by andibraeu** [comment]
ja, jetzt wo du trunk sagst, da hatte ich auch immer mal bei zwischenversionen probleme mit lua

**Comment by glycoknob** [comment]
Ich teste heute nochmal mit ChaosCalmer - Trunk scheint da an enigen stellen Probleme zuhaben.

**Comment by glycoknob** [comment]
Problem tritt nur im trunk auf - hier auch die Frage: Schließen?

**Comment by andibraeu** [comment]
schreib vielleicht eher mal an die luci-liste, oder kannst du daraus einen qualifizierten Bug machen?

**Comment by glycoknob** [comment]
jetzt auch unter CC :/

**Comment by andibraeu** [comment]
das scheint mir aber kein Problem auf unserer Seite zu sein, sondern eher etwas von luci/lua

**Comment by andibraeu** [comment]
wie kompilierst du eigentlich? vielleicht kommen die Fehler auch daher. Versuch es doch bitte nochmal auf einer "sauberen" Umgebung

**Comment by glycoknob** [comment]
Ich versuch mal nen Bug-Report zu erstellen, bau mit dem builder - also müsste alles in Ordnung sein, kann sein, dass es am neuen Ubuntu oder so liegt.

**Comment by glycoknob** [comment]
Mit Ubuntu 14.04 und CC läuft alles.

**Comment by andibraeu** [comment]
hab heute auch nochmal durchkompiliert und die Seite funktioniert... Ich mach erstmal zu
