### ISSUE TITLE
Test auf schwaches Passwort (admin) funktioniert nicht.

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#187]
Passwort ist gleich (admin), aber Hash ist immer unterschiedlich - gibt noch ein Salt wie es aussieht. 

Der Test in https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-addons/etc/profile.d/kalua.sh#L16 funktioniert so nicht. 

```
root@netbox:~ cat /etc/shadow
root:$1$FLuGYCpI$rxucSh633a9SCLqdAoFXK/:16767:0:99999:7:::
daemon:*:0:0:99999:7:::
ftp:*:0:0:99999:7:::
network:*:0:0:99999:7:::
nobody:*:0:0:99999:7:::
root@netbox:~ passwd
Changing password for root
New password: 
Bad password: too short
Retype password: 
Password for root changed by root
root@netbox:~ cat /etc/shadow
root:$1$s4Wags/y$M5Z5sMF/PGwD3djsaeBSq0:16767:0:99999:7:::
daemon:*:0:0:99999:7:::
ftp:*:0:0:99999:7:::
network:*:0:0:99999:7:::
nobody:*:0:0:99999:7:::
```

**Comment by bittorf** [comment]
danke, kuemmere mich darum.

**Comment by andibraeu** [comment]
gibts hier ideen?

**Comment by glycoknob** [comment]
zum vergleichen müssten wir den hash mit dem salt selbst berechnen...  das hier könnte klappen: http://comments.gmane.org/gmane.linux.busybox/3664 

wäre allerdings ne busybox config-option, platzmäßig kostet das wohl nichts - ich würd mal testen obs klappt

**Comment by glycoknob** [comment]
mkpasswd klappt. 
awk (sorry :) 

    salt=$(awk -F"$" '/^root/ { print $3}' < /etc/shadow)
    pass=admin
    weakhash=$(mkpasswd -5 -S $salt $pass) 
    hash=$(cat /etc/shadow | awk -F":" '/^root/ { print $2}')
    [ "$weakhash" = "$hash" ]] && echo "change passwd plz!"

**Comment by bittorf** [comment]
ja, ist klar. wir muessen dann halt mkpasswd mit ins image nehmen.
jetzt stellt sich die frage: machen? oder das feature ("schwaches passwort erkennen") einfach rausstreichen?

**Comment by andibraeu** [comment]
ich würde das auf später verschieben

Wir können in der Doku nochmal gesondert darauf hinweisen

**Comment by bittorf** [comment]
ok, ich werde trotzdem den code erstmal in profile.d drinlassen und spaeter anpassen auf mkpasswd (wenn installiert) - ticket erstmal offen lassen

**Comment by andibraeu** [comment]
Hab das in #215 verschoben
