### ISSUE TITLE
don't route rfc1918 networks to vpn server

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#19]
if your freifunk router is behind a home networks, that's usually a private one, you can't access your private resources, because, the vpn client will route this traffic to our rootserver

We need to add some lines like 

    ip rule add to 192.168.0.0/16 prio 30001 lookup main

to /etc/kalua/vpn

**Comment by glycoknob** [comment]
Gefixt seit 2015: https://github.com/weimarnetz/weimarnetz/commit/a8f8b7504fcaf4582c767693881bc2c679903348
