### ISSUE TITLE
Splashpage überarbeiten

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#194]
Aktuelle aus Wiki entfernen

**Comment by storchi** [comment]
woher sollen dann "wichtige" infos für die splashpage kommen?

**Comment by bittorf** [comment]
momentan ist es doch so, das die "neuigkeiten" vom wiki runtergeparst werden, oder? koennte man das nicht vom server selbst in ein JSON werfen lassen und nur das abholen?

**Comment by andibraeu** [comment]
Von da: http://www.weimarnetz.de/inc/feed/feed.php

Das liest unsere fb-Posts aus. Wir könnten auch die Mailingliste einbinden. Das ersetzt dann 2 Punkte

**Comment by bittorf** [comment]
komisch, für mich *sieht* das wie die mailingliste aus. ein convert nach JSON koennte ich machen, soll ich?

**Comment by andibraeu** [comment]
> komisch, für mich sieht das wie die mailingliste aus. ein convert nach JSON koennte ich machen, soll ich?
> 
Stimmt, Das ist unser rss Sammler, der beides einsammelt. 

Converter brauchst du nicht bauen. Das Ding kann in der neuen version auch json. Ich bau das heute Abend ein.

**Comment by andibraeu** [comment]
so, jetzt aber :-)

Facebook:
http://weimarnetz.de/inc/feed/feed.php?source=fbweimarnetz&format=json

ML:
http://weimarnetz.de/inc/feed/feed.php?source=mlweimarnetz&format=json

beides:
http://weimarnetz.de/inc/feed/feed.php?format=json

**Comment by andibraeu** [comment]
achso, und jsonp geht auch: http://weimarnetz.de/inc/feed/feed.php?source=fbweimarnetz&format=json&callback=function

**Comment by andibraeu** [comment]
erledigt: https://github.com/weimarnetz/openwrt-packages/commit/5aba6563bdf4746cb4372e6ebc4a81faf58d3868

Läuft auf dem MR-Router und kann per opkg update installiert werden und wird ins meshkit gebacken

**Comment by bittorf** [comment]
wunderbar.

**Comment by kaese77** [comment]
1 mit Bienchen!
