### ISSUE TITLE
Updates: /etc/config/system enthält doppelte Sections

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#199]
Ursache: Wechsel des Schemas für Benennung von Sections, betroffen sind:
```
config weblogin 'weblogin'                                    
config profile 'profile'                                      
config monitoring 'monitoring'                                
config fwupdate 'fwupdate'                                    
config vpn 'vpn'
```

Altes Schema:
```
config weblogin
config profile
config monitoring
config fwupdate
config vpn
```

Lösung: Nach Erzeugung von /etc/config/system sicherheitshalber die Sections nach dem alten Schema löschen. Muss getestet werden, damit wir die richtigen Sections löschen

**Comment by bittorf** [comment]
zeig mal die ausgabe von 'uci show system' mit doppelten eintraegen.
und: wo passiert das loeschen? in apply_profile?

**Comment by andibraeu** [comment]
müssen es doch nicht unbedingt löschen, hab die zugriffe auf die variablen umgestellt

**Comment by andibraeu** [comment]
läuft...
