### ISSUE TITLE
Käferbericht: Aliase wie z.B. n und lr funzen nicht

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#204]
Aliase aus /etc/profile.d/kalua.sh werden nicht gesetzt

**Comment by andibraeu** [comment]
da liegt der Hase im Pfeffer: https://github.com/weimarnetz/weimarnetz/blob/GebrannteMandeln/openwrt-addons/etc/kalua_init.user#L90

**Comment by glycoknob** [comment]
hmm, der neue profile.d support ist durch eine ältere /etc/profile überschrieben, frag mich nur woher die kommt: 

original: 

```
root@netbox:~ cat /rom/etc/profile
#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner
[ -e /tmp/.failsafe ] && cat /etc/banner.failsafe
fgrep -sq '/ overlay ro,' /proc/mounts && {
        echo 'Your JFFS2-partition seems full and overlayfs is mounted read-only.'
        echo 'Please try to remove files from /overlay/upper/... and reboot!'
}

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

[ -n "$FAILSAFE" ] || {
        for FILE in /etc/profile.d/*.sh; do
                [ -e "$FILE" ] && . "$FILE"
        done
        unset FILE
}
```

aktuell: 

```
root@netbox:~ ls -l /etc/profile
-rw-rw-r--    1 root     root           972 Sep 12 15:13 /etc/profile
```

```
#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner
[ -e /tmp/.failsafe ] && cat /etc/banner.failsafe

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
alias ll='ls -la'
alias flush='echo flushing_caches; echo 3 > /proc/sys/vm/drop_caches'
alias lr='logread'
alias regen='/etc/kalua_init ;. /tmp/loader'
[ -e /tmp/loader ] && . /tmp/loader
alias n='wget -qO - http://127.0.0.1:2006/neighbours'
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\] "
alias myssh='echo "executing: ssh -i /etc/dropbear/dropbear_dss_host_key"; ssh -i /etc/dropbear/dropbear_dss_host_key'
```

**Comment by glycoknob** [comment]
einfachste Lösung wäre die Datei aus dem /rom beim apply_profile.code rüberzukopieren.

**Comment by bittorf** [comment]
die ältere /etc/profile kommt aus einem sysupgrade. es gibt auch einen patch dazu, da wurde aber bisher nicht akzeptiert: https://patchwork.ozlabs.org/patch/528164/

ein einfacher workaround waere wirklich bei apply_profile immer die datei aus dem /rom zu holen, also
```
mv /rom/etc/profile /etc
```

**Comment by andibraeu** [comment]
ok, so läuft das auch schon mit der opkg.conf

**Comment by andibraeu** [comment]
@glycoknob ist das auf trunk?

auf einem frisch installierten CC1505 sieht die /etc/profile so aus:
```
#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner
[ -e /tmp/.failsafe ] && cat /etc/banner.failsafe

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
```

**Comment by andibraeu** [comment]
@bittorf in /etc/kalua_init.user erfolgt ja auch ein Aufruf von /etc/profile.d/kalua.sh, siehe https://github.com/weimarnetz/weimarnetz/issues/204#issuecomment-163037052
allerdings

**Comment by bittorf** [comment]
@andibraeu die variable $OPENWRT_REV wird durch den 'loader' gesetzt.
"echo $OPENWRT_REV" sollte also was ausgeben.
die
/etc/profile die du da gesendet hast, hat noch keinen support fuer profile.d - das koennte man reinpatchen: https://patchwork.ozlabs.org/patch/514352/

**Comment by glycoknob** [comment]
@bittorf das wäre wohl die beste Lösung, ich schieb den Patch mal in den Builder. Dann noch die Datei aus dem ROM kopieren und alles ist schön oder?

**Comment by andibraeu** [comment]
@bittorf wenn ich den loader loade gibt das ```echo``` auch die korrekte $OPENWRT_REV aus. wenn ich dann allerdings /etc/kalua_init.user aufrufe, bleibt die Variable im Script trotzdem leer. Darin wird der Loader auch gar nicht aufgerufen...

**Comment by glycoknob** [comment]
Also der Patch ist in trunk aber nicht in CC oder?

**Comment by bittorf** [comment]
@andibraeu die datei /etc/kalua_init.user darf nur von /etc/kalua_init aufgerufen werden. die ist quasi teil der infrastruktur um den 'loader' zusammenzubauen:

ls -l /etc/kalua_init*

**Comment by bittorf** [comment]
@glycoknob ja, ich glaube das fehlt in CC. entweder man strengt einen backport an oder man macht es einfach selbst rein. ich halte es auf jeden fall fuer sinnvoll das drin zu haben.

**Comment by andibraeu** [comment]
@bittorf dann scheint da trotzdem noch ein fehler drin zu sein. Kannst auf diesem Router nachgucken: 10.63.76.97

Meine Vermutung, das funktioniert nirgends, und nur wegen der alten /etc/profile vom sysupgrade haben wir die Aliase auf unseren Routern

**Comment by bittorf** [comment]
ich pruefe

**Comment by bittorf** [comment]
das stimmt, erst ein
```
. /tmp/loader
. /etc/profile.d/kalua.sh
```
bringt die loesung.
ich bin dafuer den profile.d-support aktiv reinzunehmen und den hack mit
```
mv /rom/etc/profile /etc
```
in apply_profile zu machen.

**Comment by storchi** [comment]
Am 09.12.2015 um 10:02 schrieb Bastian Bittorf:
> das stimmt, erst ein
>
> |. /tmp/loader . /etc/profile.d/kalua.sh |
>
> bringt die loesung.
> ich bin dafuer den profile.d-support aktiv reinzunehmen und den hack mit
>
> |mv /rom/etc/profile /etc |
>
> in apply_profile zu machen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/weimarnetz/weimarnetz/issues/204#issuecomment-163155133>.
>

gestern reichte auch ein:
. /etc/profile.d/kalua.sh

**Comment by andibraeu** [comment]
ja, ich denke auch, der Aufruf von /etc/kalua_init.user funktioniert nicht

**Comment by bittorf** [comment]
@storchi ja, weil der loader selbst ueber die "alte" (durch sysupgrade gesicherte) /etc/profile geladen wird.
@andibraeu was willst du immer nur mit der "/etc/kalua_init.user"? das ist eine datei die du nicht anfassen sollst, sondern nur /etc/kalua_init

**Comment by andibraeu** [comment]
@bittorf in dieser Datei steht drin, dass /etc/profile.d/kalua.sh aufgerufen wird. Und das passiert nicht!

**Comment by bittorf** [comment]
@andi - das liest du nicht richtig. daraus wird code generiert und das auch nur auf dem VPN-Server ("OPENWRT_REV" = 0 ). All diese /etc/kalua_init.* Dateien geben Zeile fuer Zeile den 'loader' aus - es wird also TEXT generiert.

**Comment by bittorf** [comment]
ich habe eine idee fuer einen workaround und sende einen pullrequest

**Comment by andibraeu** [comment]
klappt noch nicht ganz: erst wenn ich . /tmp/loader aufrufe wird kalua.sh geladen

**Comment by bittorf** [comment]
ok verstanden, das fixe ich noch

**Comment by andibraeu** [comment]
geht immer noch nicht, aber hiermit sollte das gehen: https://github.com/weimarnetz/builder/pull/16

**Comment by andibraeu** [comment]
mit dem Patch gehts nun
