### ISSUE TITLE
Test auf schwaches Passwort

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#215]
Der jetzige Test funktioniert nicht mehr, da der Hash des Passworts gesalzen ist.

Umsetzung nun mit `mkpasswd` wie in #187 beschrieben

**Comment by glycoknob** [comment]
Mit https://github.com/weimarnetz/weimarnetz/commit/c0054abc8c40ee826023e1c4fd0fe2cfd904ed15 und [478f9af3](https://gitlab.bau-ha.us/weimarnetz/firmware/commit/22af3111097a6ef182a3861fc4de0b8d50e2f29d) im Builder müsste es klappen.

**Comment by andibraeu** [comment]
ist inzwischen gelöst
