### ISSUE TITLE
Splash usabilty 

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#220]
Live aus dem Falken mit nicht weimarnetz, nicht nerd Menschen getestet. Ist kaputt.

**Comment by glycoknob** [comment]
Also könnte vieel  einfacher sein. Ist das häkchen wirklich mandatory?

**Comment by andibraeu** [comment]
Der Nutzer muss halt den Haken aktiv setzen...

**Comment by glycoknob** [comment]
Eine einfachere Seite ohne Menü oben mit einigen klaren Sätzen und Links und einem Großen Knopf fänd ich schön - nach kurzem wilden Googlen könnte das auch mit den AGB klargehen: http://www.behrmannhaertel.de/2012/12/13/checkbox-bei-agb-bestatigung-oder-kein-hakchen-kein-problem/ 

Oder wir werfen CSS drauf - z.B. bei der bösen kommerziellen Konkurrenz sieht's so aus:  https://airfy.com/assets/new/how/demo/en/screen-wifi-1-0fcd3bd559152dc014a9a3a8281d58bd.jpg 

Ich würd mal was bauen.

**Comment by andibraeu** [comment]
Eine einfachere Seite ohne Menü oben mit einigen klaren Sätzen und Links und einem Großen Knopf fänd ich schön - nach kurzem wilden Googlen könnte das auch mit den AGB klargehen: http://www.behrmannhaertel.de/2012/12/13/checkbox-bei-agb-bestatigung-oder-kein-hakchen-kein-problem/@eins78 hatte schonmal ne Idee dazu, damit die Leute mit ihren dicken Fingern das alles treffen können. Das Menü sollte meiner Meinung nach drin bleiben. Die Seite soll schließlich auch ganz normal aufgerufen werden könnenOder wir werfen CSS drauf - z.B. bei der bösen kommerziellen Konkurrenz sieht's so aus: https://airfy.com/assets/new/how/demo/en/screen-wifi-1-0fcd3bd559152dc014a9a3a8281d58bd.jpgbin wenn dann für ein paar CSS-Häcks, z.b. auf kleinen Geräten die Infoboxen ausblenden, weil man im Captive Portal nur schwer drauf drücken will. Auf Desktops sollten die Infos schon lesbar sein. Aber ich nehm mal an, du hast das auch nur mobil betrachtet.Vorher sollten allerdings die dringlicheren Probleme bearbeitet werden. Viele Nutzer schaffen es ja, die haben wahrscheinlich nur nicht so viel Bier im Falken getrunken.

**Comment by eins78** [comment]
hier sind die Skizzen von damals™:

extrem cool were so, aber rechtlich geht es eher nicht:
![1186614_10202052538293751_538129102_o](https://cloud.githubusercontent.com/assets/134942/11812824/738bd79c-a33e-11e5-807d-320b16f6eb06.jpg)

das war dann der Kompromiss:
![1228737_10202052798020244_1715572735_o](https://cloud.githubusercontent.com/assets/134942/11812823/70936eba-a33e-11e5-83e5-1b282751e03d.jpg)

technischer Hintergrund:
- die checkbox ist in einem `label` gewrappt – browser handeln das so das ein klick aufs label auf die checkbox aktiviert (einziger weg ein grösseres click-target zu bekommen)
- mit ein bissl gebastelt lässt sich der bootstrap-button-style auf das label anwenden.
- zusätzlich kann man dann noch mit dem CSS tricksen (wie airfy), und statt der checkbox ein dem status der checkbox entsprechendes icon anzeigen.

**Comment by eins78** [comment]
@glycoknob Kannst du eine aktuelle Splashpage aufrufen und mir den Quelltext speichern und schicken? Dann könnte ich was statisches basteln.

**Comment by andibraeu** [comment]
@eins78 http://home.andi95.de:3380/cgi-bin/luci/freifunk/captive

**Comment by FreifunkUFO** [comment]
Also, mit Blick auf die vielen Splash-Seiten, die von gratis-WLANs angeboten werden bezweifle ich, dass der Haken wirklich sein muss :-o 
Wäre denn auch ein Button "nicht akzeptieren (Freifunk ohne Internet starten)" sinnvoll/machbar? Ein Texteingabefeld wäre auch toll (für Interaktionen der Freifunkenden untereinander bzw. mit dem Freifunk-Node)
@eins78 was ist eigentlich ein "Zugriff auf Meldungen und Diskussionen"? klingt ominös! Als Tourist würde ich hier zb an Facebook denken. ("Hat Weimarnetz Zugriff auf meine Timeline?")

**Comment by andibraeu** [comment]
@FreifunkUFO das ist noch ein Satz aus alten Zeiten, als tatsächlich nichts ging bevor man sich freigeschaltet hat

**Comment by mtippmann** [comment]
Splash ist Geschichte.
