### ISSUE TITLE
VPN Server - locking ist zu allg.

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#221]
ein "defekter" vpn client lockt den Server und kein weiterer client kann sich verbinden. das locking wäre besser, wenn es nur den einen client beträfe.
cs

**Comment by bittorf** [comment]
das kann ich leider nicht beheben, die beiden vpn-dateien unterscheiden sich zu stark...

**Comment by andibraeu** [comment]
auf den Server läuft Kalua, es reicht, wenn du es dort anpasst

**Comment by bittorf** [comment]
@andibraeu das ist bei mir schon geaendert, also im prinzip "nur" meine /etc/kalua/vpn-datei nehmen alle vorkommen von connection_name="n$NODENUMBER" durch "Node$NODENUMBER" ersetzen.

**Comment by andibraeu** [comment]
storchi hat das mal komplett deaktiviert und es läuft damit seit 7 tagen gut

**Comment by storchi** [comment]
Auf vpn3 ist es deaktiviert

**Comment by storchi** [comment]
vpn2 hat auch kein locking mehr.
kalua ist angepasst
