### ISSUE TITLE
Kein Wifinachbar - viele Meldungen

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#222]
Das sehe ich auf Knoten 175:

```daemon.info kalua: /usr/bin/scheduler: incoming_wifi_activity() [ERR] framecounter for wlan0 old/new: 0 = 0 timediff: 59 sec```

muss ich mir Sorgen machen?

**Comment by bittorf** [comment]
gerade geschaut: dieser router hat *keine* funknachbarn. die meldung ist also OK so.
