### ISSUE TITLE
vpn: workaround für Netze in den Ping NICHT GEHT!!!!

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#224]
muss man sich mal vorstellen, sowas.
vpn Verbindung kommt nicht zu stande.

**Comment by bittorf** [comment]
vielleicht einfach nur stur testen, ob ein verbindungsaufbau geht?:
```
_net tcp_port_reachable "$server" "$port" 'VTUN server' && echo OK
```

**Comment by andibraeu** [comment]
vor allem dem Netzwerkadmin auf die Finger hauen...

**Comment by glycoknob** [comment]
Wer sperrt denn Ping ausgehend? Das macht alles kaputt. Vor allen wenn auch Path-MTU gesperrt ist.. 

Jedenfalls: Eigentlich ist der Ping in der Firmware seit dem zufälligen Auswählen nur ein Gimmick und kann auch raus. Wir testen ja auch direkt den Port.

**Comment by andibraeu** [comment]
richtig.. wie funktioniert im olsr das mit dem dynamischen gateway? d.h. HNA für Internet wird rausgenommen, wenn kein Internet mehr da ist? ist das nicht auch mit ping?

**Comment by glycoknob** [comment]
@andibraeu laut Doku schaut der nur auf die Routing Tabelle: http://www.olsr.org/docs/report_html/node140.html
