### ISSUE TITLE
seltsamer Fehler im vpn

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#235]
3600er hat internet und hat eine Verbindung mit vpn3
alle routen sind da, olsr läuft auf dem tap0
ping auf die server vpn adresse geht nicht
_vpn restart brachte nix
alle vpn checks sind erfolgreich
ip rules sind da
reboot des routers hilft

auf den clients geht kein internet
ideen?

**Comment by bittorf** [comment]
ich denke wir sollten wirklich  testen (jede minute) ob ping auf die andere seite geht. wenn nicht: ifdown ausloesen

**Comment by bittorf** [comment]
habe versehentlich gepusht, bitte anschauen:
https://github.com/weimarnetz/weimarnetz/commit/ab195fffe5bec7e4a543a2feddeab5d400bc3f26

**Comment by bittorf** [comment]
trotzdem muss mal mal schauen, warum ein '_vpn restart' da nix bringt

**Comment by storchi** [comment]
achso, vergessen. olsr vom vpn server sagte mir:
```
Jan  7 10:07:14 vpn3 olsrd[8876]: Node 10.63.1.5 is publishing your ip 10.63.122.57 as MID!
```

**Comment by glycoknob** [comment]
> 10.63.1.5

Da stinkt irgendwas gewaltig: 

https://github.com/weimarnetz/vpnconfig/blob/5926156fc01b693e424b9980c3f0388f65ca64af/README.md#ip-schema

**Comment by glycoknob** [comment]
10.63.1.4/30 ist VPN2 

Damit gehört 10.63.1.5 zu VPN2 - dann gibt es quasi eine doppelte IP, erklärt auch warum Ping kaputt ist.

**Comment by storchi** [comment]
andy wars, der hat einen anderen router zur 122 gemacht...
an den Pranger mit ihm!

**Comment by andibraeu** [comment]
andy wars, der hat einen anderen router zur 122 gemacht... an den Pranger mit ihm!ich bedauere nichts!

**Comment by bittorf** [comment]
teeren und federn! 8-)

**Comment by bittorf** [comment]
ernstgemeinte frage: soll der  pingtest nun drinbleiben?

**Comment by storchi** [comment]
ich finde den test, ob im olsr die server ip da ist ausreichend

**Comment by bittorf** [comment]
das problem am OLSR-test ist, das die IP auch drin bleibt bei "INFINITE" und das
der test mit neueren OLSR-daemons nicht mehr funktioniert...

**Comment by glycoknob** [comment]
Ich find den pingtest gut, ist eine Art Heartbeat für IP - haben wir nicht in vtun - weil layer2 - 200 Pings pro Minute wird der Server auch überleben, aber ist schon ein wenig mehr Traffic.

**Comment by storchi** [comment]
ich gebe zu bedenken, dass in diesem unseren Fall der pingtest auch nix bringt
cs

**Comment by bittorf** [comment]
ich denke das es gut is bei schlechtem ping den server-auswahl-algo neu anzustossen. nur weil der test vor 12h serverX ausgewaehlt hat, muss das ja nicht immer die  beste wahl bleiben. in diesem speziellen fall haette der pingtest nur bedingt was geholfen...
