### ISSUE TITLE
aufräumen der /etc/init.d/-Skripte

### ISSUE THREAD

**Issue by bittorf** [weimarnetz/weimarnetz#237]
da gibt es noch fehler:

```
bastian@X301:~/software/weimarnetz$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

bastian@X301:~/software/weimarnetz$ for F in openwrt-addons/etc/init.d/*;do grep -q 'sh /etc/rc.common'$ "$F" && continue; echo $F; doneopenwrt-addons/etc/init.d/S12switch_etx
openwrt-addons/etc/init.d/S43ethers_fff+
openwrt-addons/etc/init.d/S51crond_fff+
openwrt-addons/etc/init.d/set_etc_hardware
```

bitte hier:
https://github.com/weimarnetz/weimarnetz/pull/238

**Comment by glycoknob** [comment]
Nehmen wir das Ticket hier mal als catch-all für alle Probleme - in den Logfiles waren auch noch ein paar ungereimtheiten.

**Comment by glycoknob** [comment]
noch eine Frage dazu: Würde das erzeugen der /tmp/NETPARAMS und alles in S43ethers nach /etc/kalua auslagern - netparams nach _net und ethers vielleicht in eigene Datei. Gibt da momentan noch ein Problem mit der Erstellung von /tmp/NETPARAMS und so ist's vielleicht leichter zu debuggen.

**Comment by bittorf** [comment]
@glycoknob ok, das hört sich gut an und ist sowieso auf meiner liste. ich mach das.

**Comment by bittorf** [comment]
das gleich mit "S43ethers" kommt noch.

**Comment by glycoknob** [comment]
Ich teste nochmal!

**Comment by glycoknob** [comment]
Ist nur noch `apply_profile.code` und das könnte man noch umziehen z.b. nach `/usr/sbin`

**Comment by andibraeu** [comment]
ist mit der Umstellung der apply_profile.code gelöst
