### ISSUE TITLE
Namen finden

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#245]
... und Milestones anpassen

**Comment by bittorf** [comment]
ich vermute das die neue firmware ende märz aufgespielt werden kann, daher plädiere ich
"frühlingserwachen" bzw. "knabenblütenträume" 8-)

**Comment by storchi** [comment]
immer mal locker bleiben und durch die hose atmen

**Comment by glycoknob** [comment]
knabenblütenträume ist super.

**Comment by glycoknob** [comment]
Frühling ist vorbei :)

**Comment by bittorf** [comment]
Aber jetzt kommt bald wieder Frühling...

**Comment by mtippmann** [comment]
*bump*

**Comment by mtippmann** [comment]
Seggenrohrsänger

**Comment by bittorf** [comment]
hat keinen Bezug zu Weimar.
Knabenblütenträume schon 8-)

**Comment by andibraeu** [comment]
wie wär es mal mit ernsthaften Vorschlägen?

Z.B. "Bauhaus Edition", vieles ist neu und anders und einfacher gehalten

**Comment by storchi** [comment]
bin für Brauhaus

**Comment by mtippmann** [comment]
brauhaus.
