### ISSUE TITLE
Features festlegen

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#246]

**Comment by bittorf** [comment]
OLSR2 fuer IPv6 sollte nicht weh tun.

**Comment by glycoknob** [comment]
Alles nicht sooo viel Aufwand: 
https://github.com/weimarnetz/weimarnetz/issues/46
https://github.com/weimarnetz/weimarnetz/issues/252
https://github.com/weimarnetz/weimarnetz/issues/256
https://github.com/weimarnetz/weimarnetz/issues/252
https://github.com/weimarnetz/weimarnetz/issues/240
https://github.com/weimarnetz/weimarnetz/issues/237
https://github.com/weimarnetz/weimarnetz/issues/122
https://github.com/weimarnetz/weimarnetz/issues/36

Eventuell noch:
https://github.com/weimarnetz/weimarnetz/issues/109
https://github.com/weimarnetz/weimarnetz/issues/42

**Comment by andibraeu** [comment]
Feature Freeze!!1!
