### ISSUE TITLE
respawn crond klappt nicht

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#250]
kann das mal jemand testen der ahnung hat?
cs

#249

**Comment by storchi** [comment]
man könnte auch crond aud dem oom raus nehmen:
http://backdrift.org/oom-killer-how-to-create-oom-exclusions-in-linux

**Comment by glycoknob** [comment]
Blöderweise ist es wohl nicht OOM, weil Basti hat schon für den Fall vorgesorgt und der Router reboot nach 10s wenn ein OOM aufrtitt - siehe hier: https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-addons/etc/init.d/generate_kalua_loader

Da muss irgendwas anderes Faul sein, oder das wird nicht gesetzt/funktioniert nicht. Idee ist trotzdem gut und sollten wir einbauen.

**Comment by storchi** [comment]
wie tue ich ein oom triggern?

**Comment by glycoknob** [comment]
> wie tue ich ein oom triggern?
>

     echo f > /proc/sysreq-trigger

**Comment by glycoknob** [comment]
oder auf olsr routen gehen in luci bei 32mb geräten :)  - das triggert aber mit zram seltsamerweise eben keinen OOM.... mal weiter debugger

**Comment by glycoknob** [comment]
https://github.com/weimarnetz/weimarnetz/issues/251 geht's weiter.
