### ISSUE TITLE
flashen fabrikneuer router schlägt fehl

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#255]
hatte ich jetzt 2x, 1x mit 842er und 1x nanostation loco m5
firmware geht drauf, router kommt mit 192.168.1.1 hoch und rebootet nach ca. 10s ohne sich zu konfigurieren.
bei der nanostation hab ich als workarround die stock openwrt cc geflasht und von dort aus unser gm sysupgrade -> ging
cs

**Comment by mtippmann** [comment]
Problem ist ebenfalls mit OpenWRT 15.05 verbandelt -> Mülltonne.
