### ISSUE TITLE
Meshkit / Firmware - bei nicht vorhandener Knotennummer automatisch neue Registrieren + Konfigurieren

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#260]
Der Registrator kann das. Siehe: 
https://github.com/weimarnetz/registrator#dev-implementers-walkthrough

müssten  https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-addons/usr/sbin/cron.registrator_client.sh sowie https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-build/apply_profile.code dafür anpassen.

**Comment by bittorf** [comment]
ok, mache ich.

**Comment by glycoknob** [comment]
Grad mal geschaut, da muss gar nicht so viel für angepasst werden. Ich teste mal wo es klemmt. Sowohl kalua als auch der Registrator können das schon zu 99%.

**Comment by mtippmann** [comment]
hängt an #295
