### ISSUE TITLE
_vpn Skripte haben ein Problem 

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#263]
ich sehe endlos-schleifen und konstante olsr Neustarts - Ursache ist unklar, könnte ein _watch Script script sein. Reboot hilft manchmal, manchmal nicht. Da ist irgendwas kaputt.

**Comment by andibraeu** [comment]
hast du vielleicht ein Log, eine Knotennummer?

**Comment by glycoknob** [comment]
hab ich lokal bei mir beabachtet (188) und man sieht es auch auf dem mr router (43), wenn man `_vpn restart` eintippt. man sieht in den logfiles dass olsr sich ständig neustartet, vielleicht sich das auch wieder aber scheint eine schleife zu triggern

**Comment by andibraeu** [comment]
die 43 könnte mit der doppelten Knotennummer kollidieren. Und wenn er sich mit dem gleichen VPN-Server verbindet, dann knallt es eben...

**Comment by storchi** [comment]
funzt
