### ISSUE TITLE
Zugang via Switch kaputt

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#275]
Internet via Switchport kaputt?

**Comment by bittorf** [comment]
warum? sag mal genauer was nicht geht...

**Comment by storchi** [comment]
in irgendeiner kombi infoseite an/aus und was weiss ich bekommen kabelclients kein internet
ich selbst konnte das bisher nicht nachstellen
cs

**Comment by glycoknob** [comment]
grad kommt man nicht auf das 10.63.x.x Netz via Switch. Internet geht.

**Comment by glycoknob** [comment]
läuft im master seit einiger Zeit.
