### ISSUE TITLE
Meshkit Firmware auf WDR4300v1 ist kaputt

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#277]
jffs2 lässt sich wohl nicht mounten, reboot schleife nach Factory flaschen.
mount_root - no jffs2 marker found.

**Comment by glycoknob** [comment]
Workaround: 

- Failsafe modus 
- Aktuelles LEDE Image (haben factory genommen) via Netcat vom Rechner auf Router ziehen 
- Flaschen 
- Firmware via sysupgrade draufbügeln

**Comment by andibraeu** [comment]
Ggf. Zusammenhang mit #283 ?

**Comment by glycoknob** [comment]
Das müsste in LEDE gefixt sein - wir hatten das Problem letztens auch beim flaschen der WDR4300er von Toni - OpenWrt hat irgendein Problem mit dem erstellen vom jffs2 aber nur nach einem Flash mit Factory Firmware. LEDE drüberbrügeln hat geholfen - beim 1x LEDE flaschen ist das noch nicht passiert.

**Comment by mtippmann** [comment]
tritt nur für OpenWRT 15.05 auf -> legacy -> Mülltonne.
