### ISSUE TITLE
dropbear dsa key patchen

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#281]
https://git.lede-project.org/?p=source.git;a=commitdiff;h=a4cf4c35af05d8128ca7887c4f9c6c2cb53102bb

**Comment by glycoknob** [comment]
done - https://gitlab.bau-ha.us/weimarnetz/firmware/commit/907bc062fc73c38b928155e4c0c7f58612148335  - erstmal nur im lede-17.01 branch
