### ISSUE TITLE
Stoppen der Netzwerkinterfaces für Sysupgrade

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#283]
Problem ist, dass es beim Sysupgrade im laufenden Betrieb zu gebrickten Routern kommt.

Laut Battlemesh und Gluon taucht das Problem auch anderswo regelmäßig auf und das Herunterfahren der Netzwerkinterfaces hilft

**Comment by glycoknob** [comment]
@bittorf - meinst entladen der netzwerktreiber reicht? haben wir noch was wichtiges vergessen? oder ist besser den algorithmus aus kalua zu übernehmen - alles was hilft ohne lange wartezeit wäre die idee.

**Comment by bittorf** [comment]
es gibt "/etc/kalua/firmware" und dort "firmware_burn()". das macht alles. Und läuft. Keine Ausfaelle mehr zu beklagen...

**Comment by mtippmann** [comment]
erstmal nicht mehr nötig. läuft bislang stabil.
