### ISSUE TITLE
Gebrannte Mandeln mit 15.05.1 bauen und in Meshkit einbauen

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#287]
Dann hätten wir Support für 841 v11

Ggf. prüfen, ob die richtigen Bibliotheken für olsr gesetzt sind

**Comment by glycoknob** [comment]
wie ist hier der Stand? Wir könnten auch GebrannteMandeln mit LEDE laufen lassen.

**Comment by glycoknob** [comment]
Müssten wir aber mal testen u.A. wegen OLSR-Bibliotheken.

**Comment by mtippmann** [comment]
mittlerweile auch obsolet, 18.06 mit aktueller firmware im meshkit wäre aber schön...
