### ISSUE TITLE
Doku / Changelog für Änderungen

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#288]
Wäre gut, wenn es definitives Dokumentationsdokument gäbe wo alles wichtige steht.

**Comment by glycoknob** [comment]
Das Wiki hier dürfte genügen: https://github.com/weimarnetz/weimarnetz/wiki/

**Comment by mtippmann** [comment]
weimarnetz.github.io ebenfalls

**Comment by mtippmann** [comment]
read the source luke, leider erstmal...
