### ISSUE TITLE
netifd proto für vtun

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#292]
jetzt oder nie - erlaubt es auch eventuell mal später den vpn zu wechseln und viel nach uci auszulagern - inspiration sind die scripte für wireguard und openvpn - anlegen der ip rules ist noch nicht klar, alles andere müsste machbar sein.

**Comment by glycoknob** [comment]
sobald das läuft merge ich den ffwizard branch in nextrelease dann können wir luci/owm dranbauen und größer testen.

**Comment by glycoknob** [comment]
Ist mit #282 verbandelt.

**Comment by mtippmann** [comment]
done.
