### ISSUE TITLE
Multi VPN WAN

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#293]
Research

**Comment by glycoknob** [comment]
Mit Policy-Routing und mwan3 kommt man schon recht weit: 

https://wiki.openwrt.org/doc/howto/mwan3 

Geht von Load-Balancing der Verbindung über Failover etc.pp.  

Unrealistich, dass als Feature einzubauen. Aber zum Testen/Basteln sicherlich interessant u.A. weil man so über USB mehrere LTE-SIM-Karten nutzen könnte oder 2 DSL-Anschlüsse via Round-Robin bedienen könnte. 

Man könnte probieren kompatibel mit mwan3 zu bleiben. Solange es aber keinen konkreten Grund gibt, dass zu nutzen eher nicht. 

Generell sieht das hier interessant aus: https://youtu.be/LTHLbdkdCjE?t=1009

**Comment by mtippmann** [comment]
nope.

**Comment by mtippmann** [comment]
okay, bleibt erstmal als idee hier.

**Comment by mtippmann** [comment]
unrealistisch im moment.
