### ISSUE TITLE
owm.lua reparieren / updaten

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#294]
Einige Funktionen wie arptable wurden umbenannt. Siehe https://github.com/openwrt/luci/commit/366707a681459a4d520dc97024ea0a4b3c24a326

**Comment by mtippmann** [comment]
nochmal mit trunk testen.

**Comment by andibraeu** [comment]
aus luci.sys nutzen wir keine der weggefallenen Funktionen mehr. Gibt es hier noch was zu tun?

**Comment by andibraeu** [comment]
die olsr-nachbarn sind ja da, es fehlen die ip/netzwerk-nachbarn...
