### ISSUE TITLE
registrator ubus interface

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#295]
Wenn der registrator ubus kann, dann können wir bequem den Status über owm.lua abfragen und auch in Luci verlässliche Infos zur Knontenummer rausgeben.

**Comment by mtippmann** [comment]
nice to have, geht evtl. auch ohne. wäre gut für lua api. siehe https://wiki.openwrt.org/doc/techref/ubus#lua_module_for_ubus

**Comment by mtippmann** [comment]
uclient-fetch kann keinen request body von 40x und 50x responses ausgeben, plan wäre luci-lib-httpclient zu nutzen und das ganze als ubus rpcd service zu basteln...

**Comment by mtippmann** [comment]
sieht z.B. so aus: https://github.com/weimarnetz/packages/blob/master/utils/luci-app-owm/files/owm.lua

**Comment by andibraeu** [comment]
Schritt 1: Registratorclient auf lua umbauen
Schritt 2: in rpcd einbinden

**Comment by andibraeu** [comment]
noch zu tun:

- [ ] rpcd-scripte erstellen
- [ ] owm.lua fragt rpcd nach und gibt die aktuelle lokale Knotennummer und die Antwort von Registrator zurück. Damit könnten wir sehen, wenn sich die registrierte Knotennummer von der aktuell gewählten Knotennummer unterscheidet
