### ISSUE TITLE
CI für Code.

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#299]
Shellcheck laufen lassen? 
Unit-Tests? Ginge mit sowas wie [bats](https://github.com/sstephenson/bats) 
Firmware-Image automatisch bauen lassen?

**Comment by glycoknob** [comment]
https://github.com/kward/shunit2

**Comment by bittorf** [comment]
https://github.com/bittorf/kalua/tree/master/tests

**Comment by mtippmann** [comment]
plan ist buildbot auf buildbot.weimarnetz.de via m18 server. todo.

**Comment by mtippmann** [comment]
wir haben einen buildbot auf buildbot.weimarnetz.de
