### ISSUE TITLE
_watch_vpn: Prüfung auf 10.63.1.1-10.63.1.63 festzurren

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#31]
Sonst möglicherweise Konflikte mit Knoten 256 (10.63.1.65)

**Comment by storchi** [comment]
neues vpn ip schema

**Comment by bittorf** [comment]
hier gehts nicht vorwaerts, habs mal gemacht: 03f07fee8e49e2d8ae188d1e4cdba9bd509b92af
