### ISSUE TITLE
SSID wechseln -> Kaputt!? 

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#311]
in /etc/config/profile...

ffwizard -> Gerät bootet nicht mehr. 

Router: TP-Link 1043Nv5

**Comment by mtippmann** [comment]
Muss getestet werden.

**Comment by mtippmann** [comment]
Mit Firmware nachstellen.

**Comment by andibraeu** [comment]
hat heute bei mir funktioniert mit einem WDR4300, Knoten 31

SSID für beide Radios geändert -> auf den Knopf gedrückt -> 30 Sekunden gewartet -> fertig -> SSIDs gesetzt und angezeigt

Ich habe es für die Konfigurationsseite getan
