### ISSUE TITLE
Router hängt beim Booten

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#312]

**Comment by bittorf** [comment]
klingt evtl. nach Flash voll? Schon neue erkenntnisse? Kein ping? Kein ssh? kein web?

**Comment by kaese77** [comment]
Nein, bisher nichts Neues. Trat bei beiden 1043n-v5 auf. Node 739 und 740.

**Comment by mtippmann** [comment]
Bislang nicht wieder aufgetaucht - liegt eventuell am C60v2 wo Support noch wackelig war.
