### ISSUE TITLE
SSID Konfigurieren / wird überschrieben

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#314]
via Luci, sysupgrade fest.

**Comment by mtippmann** [comment]
check einbauen sollte sowohl sysupgrade wie auch ffwizard überstehen. `/etc/config/wireless`

**Comment by mtippmann** [comment]
SSID darf nicht überschreiben werden.

**Comment by mtippmann** [comment]
- Alte SSID durch Scripte in uci-defaults auslesen und in uci/ffwizard eintragen 
- ffizward.d Scripte sollten den Eintrag aufgreifen und die korrekte alte SSID-Setzen 
- Weimarnetz.Freifunk SSID bleibt davon unberührt.

**Comment by andibraeu** [comment]
Konfiguration SSID erfogt dann in #326

**Comment by andibraeu** [comment]
bitte testen!

**Comment by mtippmann** [comment]
läuft. danke!
