### ISSUE TITLE
knotennummer wird nicht registriert

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#322]

**Comment by andibraeu** [comment]
seit 64955f8be348d859c500d8a0772618b6490c5c92 sollte das gehen

**Comment by mtippmann** [comment]
muss noch getestet werden.

**Comment by andibraeu** [comment]
das sollte jetzt laufen, oder?

**Comment by mtippmann** [comment]
läuft. danke nochmal!!!
