### ISSUE TITLE
VPN muss konfigurierbar sein

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#323]
- Alles immer über VPN, sonst kein Internet 
- Opportunistisch VPN wenn verfügbar sonst trotzdem Internet 
- Kein VPN, nur zur Verbindung der anderen Knoten 

- komplett VPN ausschalten sollte es nicht geben, weil man so immer über das Netz an den Router kommt auch wenn das Internet direkt ausgeleitet wird.

**Comment by mtippmann** [comment]
auch über Luci-Konfigurierbar machen.

**Comment by andibraeu** [comment]
für luci siehe #326

**Comment by mtippmann** [comment]
funktioniert noch nicht, iptables regeln werden noch falsch gesetzt.
