### ISSUE TITLE
OpenWrt SDK / Imagebuilder benutzen anstatt alles komplett immer wieder zu konfigurieren. 

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#325]
spart sehr viel Build-Zeit, wir können Bug-Reports eher an OpenWrt-stellen evtl. Binarkompatibilität und leichteres Installieren von externen Paketen über feeds dadurch.

**Comment by andibraeu** [comment]
erledigt: https://github.com/weimarnetz/firmware/issues/21
