### ISSUE TITLE
Weimarnetz Konfigurationsseite erneuern

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#326]
- [x] Knotennummer eintragen, wenn keine vorhanden ist (frisch geflasht)
- [x] Knotennummer ist über Weboberfläche nicht änderbar
- [x] Status aus Registrator wird angezeigt
- [x] SSID für eigenen AP festlegen (Default ist Weimarnetz <Knotennummer>)
- [x] VPN-Schalter für "VPN aus", "VPN Cloud Connect", "VPN The full monty"
- [x] Kontaktdaten auf Karte veröffentlichen? (Default=off)

**Comment by andibraeu** [comment]
die Knotennummer in der luci-web-app anzugeben macht derzeit wenig Sinn. Das ginge nur, wenn der Router noch keine Nummer registriert hat. Das macht er aktuell aber sobald er Internet hat.

Brauchen wir das Feature also?

**Comment by kaese77** [comment]
Fänd ich schon gut, falss er kein Internet hatte bei der ersten Einrichtung.

VG, René

**Comment by andibraeu** [comment]
Wenn wir weiter übers Meshkit Images ausliefern ist die Knotennummer aber auch schon da.

Klingt wie ein Edge-Case der jetzt kein Showstopper für Production ist :D
