### ISSUE TITLE
vtun muss olsr neustarten

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/weimarnetz#329]
sonst kein internet

**Comment by andibraeu** [comment]
guck mal @mtippmann 

reicht das schon so? https://github.com/weimarnetz/weimarnetz/commit/7400e88a30e8d4c6bafbde5f49aeacfb4518d8c6

Oder sollte der Neustart woanders erfolgen?

**Comment by mtippmann** [comment]
hmm, vtun-up ist vielleicht auch der falsche ort dafür, denke das passt so.
