### ISSUE TITLE
Link quality brake down

### ISSUE THREAD

**Issue by L337hium** [weimarnetz/weimarnetz#34]
We see some issues while transferring data over weak links.

On the mailinglist we discussed that `tc` and sven-ola's script might help. See: http://www.weimarnetz.de/newsgroups/article.php?id=3922&group=freifunk.de.weimar.discuss

**Comment by glycoknob** [comment]
Wir könnte noch WMM testen: 

<kopie aus mail>

WMM ist QoS auf WLAN-Ebene: 
http://wireless.kernel.org/en/developers/Documentation/mac80211/queues
http://en.wikipedia.org/wiki/Wireless_Multimedia_Extensions

Da gibt es 4 Prioritätsklassen und man kann Pakete in verschiedene Klassen mit iptables taggen: 


    iptables -t mangle -A OUTPUT -p udp –dport 698 -j DSCP –set-dscp 63

Soweit ich das verstehe ist WMM per default aktiviert und mac80211 kann das auch im Ad-Hoc Modus... 

Mit debugfs für ath9k/mac80211 sieht man zumindest, dass verschiedene Queues gibt: 

     root@ffweimar-hybrid-dhcp-195:/sys/kernel/debug/ieee80211/phy0/netdev:wlan0 cat hw_queues 
    AC queues: VO:0 VI:1 BE:2 BK:3

bei download von /dev/null sieht man auch, dass das einsortiert wird: 

normal - alles landed in der BE queue: 

    root@ffweimar-hybrid-dhcp-195:/sys/kernel/debug/ieee80211/phy0/ath9k cat queues 
    (VO):  qnum: 3 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
    (VI):  qnum: 2 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
    (BE):  qnum: 1 qdepth:  1 ampdu-depth:  1 pending:  11 stopped: 0
    (BK):  qnum: 0 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
    (CAB): qnum: 8 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0


    iptables -t mangle -A OUTPUT -p tcp –sport 80 -j DSCP –set-dscp 63 

jetzt sind die Pakete in der höchsten? Stufe.. 

    root@ffweimar-hybrid-dhcp-195:/sys/kernel/debug/ieee80211/phy0/ath9k cat queues 
    (VO):  qnum: 3 qdepth:  9 ampdu-depth:  0 pending:  25 stopped: 0
   (VI):  qnum: 2 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
   (BE):  qnum: 1 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
   (BK):  qnum: 0 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0
   (CAB): qnum: 8 qdepth:  0 ampdu-depth:  0 pending:   0 stopped: 0

**Comment by glycoknob** [comment]
Wir haben tc mit prio qdsic dafür... wenn das Problem noch da ist, nochmal nen Ticket aufmachen!
