### ISSUE TITLE
842er v2 geo koordinaten von osm werden nicht ins formular übernommen...

### ISSUE THREAD

**Issue by storchi** [weimarnetz/weimarnetz#342]
sad
firmware: http://buildbot.weimarnetz.de/builds/brauhaus/reboot2020-19.07-beta.1-28-g20e20ba%2Bopenwrt-r11063-85e04e9f46/ath79/generic/weimarnetz/ffweimar-openwrt-ath79-generic-tplink_tl-wr842n-v2-squashfs-factory.bin

mfg

**Comment by storchi** [comment]
browser: chrome auf linux

**Comment by andibraeu** [comment]
ist mir auch schon aufgefallen

**Comment by andibraeu** [comment]
und das gehört wahrscheinlich eher dahin: https://github.com/freifunk/openwrt-packages/pulls
