### ISSUE TITLE
use 10.64.x.y for 2nd wifi device // macvlan 

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#36]

**Comment by glycoknob** [comment]
Wie wäre es damit: 

    a typical node 16:
    all:  10.63.16.0  /26  (=  0...64)
       + 10.64.16.0  /26  (=  0...64)
    WIFI24: 10.63.16.0  /27  (=  1...30) = 29 x DHCP
    LAN:  10.63.16.32 /28  (= 33...46) = 13 x DHCP
    MESH24: 10.63.16.48 /29  (= 49...54) =  6 x DHCP 
    VPN:  10.63.16.56 /30  (= 57...58) =  1 x here, 1 x remote
    WAN:  10.63.16.60 /30  (= 61...62) =  1 x here, 1 x remote
    WIFI5: 10.64.16.0  /27  (=  1...30) = 29 x DHCP
    MESH5: 10.64.16.32 /27  (= 49...54) =  29 x DHCP

- sauberes Routing und richtige Zuordnung Interface/Subnetz - da könnte man auch Firewall-Zonen nutzen etc.pp
- DHCP für Adhoc würde wieder laufen (iPhones, Notebooks müssten damit klarkommen, mal testen..)
- 1:1 Mapping von 10.63.x.y IP auf 10.64.x.y 
- kein Bridging

Geräte mit mehr als 2 Radios gehen nicht, geht jetzt allerdings auch nicht wie oft wird das vorkommen? Selbst die neusten ac Router haben nur 2 Radios... bis dahin gibt es v6

**Comment by L337hium** [comment]
Das sieht aus als liesze es sich 'leicht' ins aktuelle system einbauen. Sieht gut aus.

**Comment by bittorf** [comment]
mal relayd anschauen...problem was ich momentan habe: wir braeuchten mehrere HNA-Ankuendigungen und damit kommen viele skripte nicht klar.

**Comment by bittorf** [comment]
ich bin immer noch dafuer den DHCP-Bereich von WIFI2_ap+WIFI5_ap per 'kmod-macvlan' zusammenzuführen. Vorteil: alles bleibt wie es ist (es gibt nur einen wlan-dhcp-bereich) alle skripte kommen damit klar, nur eine HNA4-ankuendigung und leichter zu verstehen...

**Comment by glycoknob** [comment]
kmod-macvlan ist echt cool. Hätten wir ja auch gleich Roaming

**Comment by bittorf** [comment]
@glycoknob ja, roaming ist ein abfallprodukt.

**Comment by glycoknob** [comment]
*bump*

**Comment by bittorf** [comment]
ich habe ja den roaming-IP bereich momentan bei mir auf 100.64.0.0/10 festgezurrt. kann es sein, das es dafuer noch regeln am VPNer geben muss?

**Comment by storchi** [comment]
Am 21.10.2016 um 08:34 schrieb Bastian Bittorf:
> ich habe ja den roaming-IP bereich momentan bei mir auf 100.64.0.0/10
> festgezurrt. kann es sein, das es dafuer noch regeln am VPNer geben muss?

wir im wn haben keine 100er adressen
cs

**Comment by bittorf** [comment]
das sind wir wieder beim "wir". es gibt ca. 70 router damit...

**Comment by storchi** [comment]
schlimm genug. was haste denn vor / was geht denn nicht?

**Comment by glycoknob** [comment]
100.64.0.0/10 würd ich auch gerne in die Weimarnetz Firmware einbauen, wenn macvlan und so laufen.

**Comment by storchi** [comment]
halte ich nix von. ein roaming über die gleiche ssid langt völlig und macht die konfig einfacher.
ein 100.64.0.0/10 netz passt auch nicht in den freifunk kontext, der ja nur 10.stadt.x.x vorsieht.

**Comment by bittorf** [comment]
christian: konfigurier doch einfach mal 2 weimarnetzrouter fuer roaming ueber die gleiche SSID,
am besten 2 router mit 2.4 und 5 GHz. Nutze dazu den vorhandenen IP-Adressebereich. Zeige uns dann die Konfig. Ich weiss nicht warum hier ueberhaupt diskutiert wird, wir drehen uns seit ewigkeiten im Kreis und es geht nicht voran...

**Comment by storchi** [comment]
kann ich dir sagen: weil das hier kein einmannunternehmen ist...

**Comment by kaese77** [comment]
Dann ist das doch eine schöne Aufgabe für Die, vor Krautchan und Videoschauen!

just my 2 cent,

René

**Comment by glycoknob** [comment]
Rein pragmatisch: Mit 10.63.x.y/26 haben wir nur nur maximal 64 Adressen pro Knoten, durch die Aufteilung sind davon maximal 29 für WLAN Clients nutzbar - die Frage ist halt ob das genügt. Wir wissen nicht mal ob wir das überhaupt erreichen. Aber mit Smartphones und bei Veranstaltungen dürfte das IMHO zu wenig sein für einen Router mit 2.4+5GHz.

Eine Idee wäre 100.64.0.0/10 nur für die SSID `weimar.freifunk.net` zu nehmen und es gibt weiterhin `Weimarnetz Knoten FooBarBaz` mit dem Bereich aus 10.63.x.x - LAN und AdHoc bleiben gleich bzw. kann man sich auch via Ad Hoc eine IP ziehen. 

Ein Problem ist auch, dass Roaming mit den 10.63.x.x Adressen im Prinzip auch ginge, aber so wie es in kalua realisiert ist, weiß ich nicht ob das klappt. Dort ist es so, dass das jeder Router alle Adressen aus dem Netz  100.64.0.0/10 akzeptiert, aber nur die IP-Adressen für ein /24 verteilt - eine Adresse aus einem anderen /24 aus dem Block wird trotzdem geroutet - zudem gibt es einen "fake" Gateway der überall gleich ist - z.b. 10.64.254.254 damit die Clients keinen neuen DHCP Lease benötigen. Weiterhin wird durch macvlan alles auf Layer 2 identisch gemacht, gleiche ARP Adresse, gleiche BSSID/SSID damit das reibungslos läuft. 

100.64.0.0/10 "ranpappen" wäre wohl tatsächlich einfacher, eine tolle Lösung ist das auch nicht, aber so würde alles andere einfach weiterlaufen.

**Comment by kaese77** [comment]
Ne Bridge für WLAN und Switch-Ports??? Ist doch einfacher, oder nicht?


René

**Comment by glycoknob** [comment]
2016-10-28 16:05 GMT+02:00 kaese77 <notifications@github.com>:

> Ne Bridge für WLAN und Switch-Ports??? Ist doch einfacher, oder nicht?
>

Das Problem ist, dass die IP-Adressen für den VPN im Moment auch
festgezurrt sind und man noch ein Netz für AdHoc braucht das unabhängig von
anderen Netzen ist.

Man könnte jetzt alles in das WLAN-Netz bridgen, dann hätte man aber man
aber für LAN und co. nur 29 IPs/Knoten - alternativ könnte man probieren 2
Subnetze pro Interface zu haben, das müsste gehen aber bin mir nicht ganz
sicher wie das im Detail funktioniert, tendenziell eher nicht so richtig
und wohl nicht mit uci out of the box

AdHoc kann definitiv nicht in die Bridge:
https://dev.openwrt.org/ticket/10108 - das müsste noch aktuell sein.

Jetzt haben wir das Problem, dass das /26 irgendwie aufgeteilt werden
muss... eigentlich geht nur ein /27 mit den 29 Adressen als Bridge mit
einem Netz... gerade ist das zweite /27 noch aufgeteilt - siehe weiter
oben.

Für den Moment ist es wohl einfacher das via Routing zu machen und ggf.
einen Knopf einzubauen, damit LAN Ports auch über das VPN gehen.

Das müsste eine ip rule regel sein, die wird momentan im _vpn start script
gesetzt in der geschriebenen vtund.conf - dort müsste man noch eine
zusätzliche ip rule für das Ethernet Subnetz einbauen.

Das 100.64.0.0/10 Netz ist dafür auch nicht gut, weil wir damit den Zugriff
über Intercity-VPN auf Dienste am Router verlieren, bzw. eigene Suppe
kochen ohne Not. Für WLAN-Clients am AP kann drüber diskutieren, weil die
eher selten Dienste anbieten und man ggf. noch ein AP im 10.63.x.x Netz
anbieten kann, aber sonst klappt das nicht.

**Comment by bittorf** [comment]
An die laberbacken: einfach mal 2 Router konfigurieren und lernen, das einfach nur die SSID gleichzumachen KEIN roaming ermöglicht. Also nicht quatschen, sondern zur Abwechslung einfach mal "machen". Wir reden jetzt seit über 2 Jahren (siehe Ticketstart) und es tut sich nichts...

Es ist klar, das dies nicht der Weisheit letzter Schluss ist, aber auf jeden Fall besser als jetzt.

**Comment by storchi** [comment]
nein, ist es nicht.

**Comment by glycoknob** [comment]
Hier geht's weiter: https://github.com/weimarnetz/weimarnetz/issues/240 

Ich mach hier mal das Ticket zu.
