### ISSUE TITLE
2.4GHz AP wird fehlerhaft konfiguriert

### ISSUE THREAD

**Issue by L337hium** [weimarnetz/weimarnetz#45]
Aktuelle weimarnetz-firmware gebaut, geflasht und mit apply_profile konfiguriert. Der Teil der Wireless-Config fuer 2.4 GHz AP / MasterMode blieb unveraendert.

Update: Handelt sich natuerlich um dual-band geraete. in dem fall tl-wdr3600

**Comment by glycoknob** [comment]
So sieht's grad aus: 

```
# uci show wireless
wireless.radio0=wifi-device
...
wireless.radio0.hwmode=11g
...
wireless.radio0.disabled=0
wireless.@wifi-iface[0]=wifi-iface
wireless.@wifi-iface[0].device=radio0
wireless.@wifi-iface[0].network=wlanadhoc
wireless.@wifi-iface[0].mode=adhoc
wireless.@wifi-iface[0].bssid=02:ca:ff:ee:ba:be
wireless.@wifi-iface[0].ssid=weimarnetz
wireless.@wifi-iface[0].mcast_rate=1000
wireless.@wifi-iface[1]=wifi-iface
wireless.@wifi-iface[1].device=radio0
wireless.@wifi-iface[1].network=wlan
wireless.@wifi-iface[1].mode=ap
wireless.@wifi-iface[1].ssid=OpenWrt
wireless.radio1=wifi-device
...
wireless.radio1.hwmode=11a
wireless.radio1.htmode=HT40+
wireless.radio1.disabled=0
wireless.@wifi-iface[2]=wifi-iface
wireless.@wifi-iface[2].device=radio1
wireless.@wifi-iface[2].network=wlanRADIO1
wireless.@wifi-iface[2].mode=adhoc
wireless.@wifi-iface[2].bssid=02:ca:ff:ee:00:40
wireless.@wifi-iface[2].ssid=weimarnetz
wireless.@wifi-iface[2].mcast_rate=6000
wireless.@auto_optimize[0]=auto_optimize
wireless.@auto_optimize[0].neigh=off
```

2.4GHz: adhoc + api - SSID falsch 
5GHz: _nur_ adhoc, kein ap... 

Ziel wäre: 

2.4+5GHz: adhoc + ap mit richtiger SSID 

der code dafür müsste hier losgehen: https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-build/apply_profile.code#L399 

...vielleicht mit http://wiki.openwrt.org/doc/devel/config-scripting überarbeiten...

**Comment by glycoknob** [comment]
hier ist das problem (und ein fix der die alte ssid wegwirft): https://github.com/glycoknob/weimarnetz/commit/7dc45ab85e421b14a0d162e3683b724093a4b1c0 ... 

müssen uns was wegen den `keepsettings=1` überlegen... siehe auch #51 #56

**Comment by andibraeu** [comment]
> 2.4GHz: adhoc + api - SSID falsch 
> 5GHz: nur adhoc, kein ap...
> 
> Ziel wäre:
> 
> 2.4+5GHz: adhoc + ap mit richtiger SSID
> 
5ghz nur adhoc ist schon richtig. DHCP bekommen wir nämlich nur auf einem Interface zum laufen. Da haben wir lang probiert und das als Kompromisslösung verwendet =

**Comment by storchi** [comment]
On 19.01.2015 07:07, Andi wrote:
> 5ghz nur adhoc ist schon richtig. DHCP bekommen wir nämlich nur auf einem Interface zum laufen. Da haben wir lang probiert und das als Kompromisslösung verwendet =

das ursprungsproblem ist tatsächlich die dhcp konfig fuer die 4 wlan 
interfaces. bisher klappte die adressvergabe nur auf max 3 interfaces. 
hat was mit broadcast zu tun, die antworten gehn auf dem falschen if 
raus. sieht man gut mit tcpdump.
als lösungsansatz wurde das 10.64.x.x netz fuer uns reserviert, um das 
evtl fuer die dual wifi geräte zu nehmen(5ghz)

cs

**Comment by glycoknob** [comment]
hab heute etwas rumprobiert und mit folgender konfig läuft dhcp für 2.4 und 5ghz (siehe auch meinen berg an emails)

br-wlan aus 2.4ghz ap und 5ghz ap... bekommt das dhcp subnetz 10.63.x.0/27 und dnsmasq kümmert sich nur darum. 

wlanadhoc2 auf 10.63.x.48/32 - kein dhcp 
wlanadhoc5 auf 10.63.x.49/32 - kein dhcp 

alles andere wie vorher... olsr scheint damit zu laufen - ich komme auf andere knoten.. bekomme per dhcp auch immer eine ip egal ob 2.4 oder 5ghz.. 

ich vermute mal die überlappenen subnetze über mehrere interfaces sind an den dhcp problemen schuld.. mit obiger konfig kann ich auch alle ips anpingen als client, was vorher nicht geklappt hat. 

das mit 10.64.x klingt auch gut.

**Comment by storchi** [comment]
Am 20.01.2015 um 03:38 schrieb glycoknob:
> br-wlan aus 2.4ghz ap und 5ghz ap... bekommt das dhcp subnetz 
> 10.63.x.0/27 und dnsmasq kümmert sich nur darum. 

dann geht aller traffic immer über beide ifs raus, oder hab ich eine 
bridge falsch verstanden?
wenn ja fänd ich das doof, weil wir uns das wlan band sinnlos zumachen

cs

**Comment by glycoknob** [comment]
```
root@ffweimar-hybrid-dhcp-196:~ ip l
...
7: br-wlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ea:94:f6:68:4b:91 brd ff:ff:ff:ff:ff:ff
8: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether e8:94:f6:68:4b:92 brd ff:ff:ff:ff:ff:ff
9: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether e8:94:f6:68:4b:91 brd ff:ff:ff:ff:ff:ff
10: wlan1-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-wlan state UP mode DEFAULT group default qlen 1000
    link/ether ea:94:f6:68:4b:92 brd ff:ff:ff:ff:ff:ff
11: wlan0-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br-wlan state UP mode DEFAULT group default qlen 1000
    link/ether ea:94:f6:68:4b:91 brd ff:ff:ff:ff:ff:ff
```

```

**Comment by glycoknob** [comment]
hier noch die konfiguration: 

```
root@ffweimar-hybrid-dhcp-196:~ cat /etc/config/wireless 
config wifi-device radio0
        option type     mac80211
        option country  US              # see hacked /usr/lib/crda/regulatory.bin
        option channel  5
#       option ath9k_chanbw 20          # temporary, 5, 10 or 20 (default)
#       option chanbw   20              # since r32596
#       option macaddr
        option frag     off
        option txpower  20
        option beacon_int 1000
#       option noscan   1
        option path 'platform/ar934x_wmac'
        option hwmode   11g
        option htmode   HT20

config wifi-iface
        option device   radio0
        option network  wlanadhoc2
        option mode     adhoc
        option bssid    '02:ca:ff:ee:ba:be'
        option ssid     'weimarnetz'
        option mcast_rate 1000
#       option bintval  1000

config wifi-iface
        option device   radio0
        option network  wlan
        option mode     ap
        option ssid     'Weimarnetz - Knoten 196'

### next radio ###


config wifi-device radio1
        option type     mac80211
        option country  US              # see hacked /usr/lib/crda/regulatory.bin
        option channel  40
#       option ath9k_chanbw 20          # temporary, 5, 10 or 20 (default)
#       option chanbw   20              # since r32596
#       option macaddr
        option frag     off
        option txpower  20
        option beacon_int 1000
#       option noscan   1
        option path 'pci0000:00/0000:00:00.0'
        option hwmode   11a
        option htmode   HT20

config wifi-iface
        option device   radio1
        option network  wlanadhoc5
        option mode     adhoc
        option bssid    '02:ca:ff:ee:00:40'
        option ssid     'weimarnetz'
        option mcast_rate 6000
#       option bintval  1000

config wifi-iface
        option device   radio1
        option network  wlan
        option mode     ap
        option ssid     'Weimarnetz - Knoten 196 | 5GHz'

config auto_optimize
        option neigh    'off'
```

```
root@ffweimar-hybrid-dhcp-196:~ cat /etc/config/network
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '0t 2 3 4 5'

config switch_vlan
        option device 'switch0'
        option vlan '2'
        option ports '0t 1'

config 'interface' 'lan'
        option 'ifname'   'eth0.1'
        option 'proto'    'static'
        option 'ipaddr'   '10.63.196.33'
        option 'netmask'  '255.255.255.240'

config 'interface' 'wan'
        option 'ifname' 'eth0.2'
        option 'proto' 'dhcp'

config 'interface' 'wlan'
        option 'type' 'bridge'
        option 'proto' 'static'
        option 'ipaddr' '10.63.196.1' 
        option 'netmask' '255.255.255.240'

config 'interface' 'wlanadhoc2' 
        option 'proto' 'static' 
        option 'ipaddr' '10.63.196.48' 
        option 'netmask' '255.255.255.255' 

config 'interface' 'wlanadhoc5' 
        option 'proto' 'static' 
        option 'ipaddr' '10.63.196.49' 
        option 'netmask' '255.255.255.255' 

config interface 'tap0'
  option ifname 'tap0'
```

**Comment by glycoknob** [comment]
andererseits... wenn das 10.64.x.x netz da ist... dann müsste man sich nicht mit bridges und eventuellen subtilen problemen herumschlagen... für die jetzige ip konfiguration wäre es aber so imho am saubersten.

**Comment by glycoknob** [comment]
hab es mal mit wireshark getestet... 1x client an 2.4ghz, 1x an 5ghz... broadcast pakete landen bei beiden... normale verbindungsdaten nicht.. also in etwas das verhalten als wenn die an einem switch hingen... wäre nicht so übel, wenn es so ist.. 

die alternative ohne das 10.64.x.x netz mit routing wäre das /27 dhcp netz in 2x /28 aufzuteilen... das wäre dann 13x dhcp für 2.4 und 13x für 5ghz... ist das genug?

**Comment by glycoknob** [comment]
okay.. vergesst das mit wireshark... monitor mode auf meinen usb stick is kaputt...

**Comment by andibraeu** [comment]
Am Dienstag, den 20.01.2015, 05:05 -0800 schrieb glycoknob:
> hab es mal mit wireshark getestet... 1x client an 2.4ghz, 1x an
> 5ghz... broadcast pakete landen bei beiden... normale verbindungsdaten
> nicht.. also in etwas das verhalten als wenn die an einem switch
> hingen... wäre nicht so übel, wenn es so ist.. 
> 
> die alternative ohne das 10.64.x.x netz mit routing wäre das /27 dhcp
> netz in 2x /28 aufzuteilen... das wäre dann 13x dhcp für 2.4 und 13x
> für 5ghz... ist das genug? 

13 sind schon recht wenig. Da wir das 10.64er Netz reserviert haben,
könnten wir sogar insgesamt ca. 60 Adressen zusätzlich vergeben, wenn
wir es geschickt benutzen ;-)

**Comment by L337hium** [comment]
Should be fixed by #91, so closed.
