### ISSUE TITLE
Apply_profile doesn't run after flashing 

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/weimarnetz#50]
1 problem could be missing /etc/hardware

Needs more investigation

**Comment by glycoknob** [comment]
Some investigation: dmesg is saved to /tmp/dmesg.boot by `/etc/init.d/S70prepare_fff\+` that runs before `apply_profile.code` that greps `dmesg` for Hardware strings... 

Not sure where the problem is... but why not just use `maschine` from `/proc/cpuinfo`? 

```
root@hvf5-salon:/etc cat /proc/cpuinfo 
system type             : Atheros AR9341 rev 3
machine                 : TP-LINK TL-WR841N/ND v8
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 266.64
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0ff8, 0x0ff8, 0x0ff8]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp dsp2
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
```

no need for a working `/tmp` or a working `dmesg.boot` file there.. no need for grepping all hardware variants in /tmp/dmesg and it should be there really early... 

If the machine field is on every router we could scrap hardware detection completly and just launch a script early in boot that writes /etc/HARDWARE 

at least for weimarnetz that should suffice?

**Comment by storchi** [comment]
On 09.01.2015 19:17, glycoknob wrote:
> Some investigation: dmesg is saved to /tmp/dmesg.boot by `/etc/init.d/S70prepare_fff\+` that runs before `apply_profile.code` that greps `dmesg` for Hardware strings...
>
> Not sure where the problem is... but why not just use `maschine` from `/proc/cpuinfo`?
>
> ```
> root@hvf5-salon:/etc cat /proc/cpuinfo
> system type             : Atheros AR9341 rev 3
> machine                 : TP-LINK TL-WR841N/ND v8
> processor               : 0
> cpu model               : MIPS 74Kc V4.12
> BogoMIPS                : 266.64
> wait instruction        : yes
> microsecond timers      : yes
> tlb_entries             : 32
> extra interrupt vector  : yes
> hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0ff8, 0x0ff8, 0x0ff8]
> isa                     : mips1 mips2 mips32r1 mips32r2
> ASEs implemented        : mips16 dsp dsp2
> shadow register sets    : 1
> kscratch registers      : 0
> core                    : 0
> VCED exceptions         : not available
> VCEI exceptions         : not available
> ```
>
> no need for a working `/tmp` or a working `dmesg.boot` file there.. no need for grepping all hardware variants in /tmp/dmesg and it should be there really early...
>
> If the machine field is on every router we could scrap hardware detection completly and just launch a script early in boot that writes /etc/HARDWARE
>
> at least for weimarnetz that should suffice?

nanostation:

root@Muentzer38-DNT-5Ghz:~ cat /proc/cpuinfo
system type		: Atheros AR7241 rev 1
machine			: Ubiquiti Nanostation M
processor		: 0
cpu model		: MIPS 24Kc V7.4
BogoMIPS		: 259.27
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 16
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0000, 0x0ff8, 
0x0ff8, 0x0ff8]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16
shadow register sets	: 1
kscratch registers	: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

**Comment by glycoknob** [comment]
Da ist noch ein anderes Problem... und zwar wird `apply_profile.code` beim booten von `apply_profile` mit dem argument `boot` aufgerufen... allerdings wird im Script irgendwo $1 für den Knotennamen verwendet... das sieht dann so aus: https://gist.github.com/glycoknob/48757c242c264c8e52f5

da sieht man, dass INSTALLATION=boot ist... 

das hier sollte mit möglichst wenigen änderungen das problem fixen (tut bei mir:) https://gist.github.com/glycoknob/48757c242c264c8e52f5

**Comment by andibraeu** [comment]
seems to work now

**Comment by bittorf** [comment]
leider ist nur fuer ar71xx das feld in /proc/cpuinfo ausgefüllt. man sollte evtl. die rueckwaertskompatibilitaet fallen lassen und direct diese dateien nehmen:

root@EG-labor-AP:~ cat /tmp/sysinfo/model 
TP-Link TL-WR1043N/ND v1

root@EG-labor-AP:~ cat /tmp/sysinfo/board_name 
tl-wr1043nd

**Comment by glycoknob** [comment]
Der aktuelle Code probiert alles mögliche durch und nimmt /proc/cpuinfo nur im Notfall: https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-addons/etc/init.d/set_etc_hardware

So richtig ideal ist das auch nicht (vor allem bei unbekannten Routern/Architekturen) 

Es gibt wohl noch /proc/cmdline - aber das ist wohl auch nicht überall vorhanden: 

    board=TL-WR841N-v8  console=ttyS0,115200 rootfstype=squashfs,jffs2 noinitrd
