### ISSUE TITLE
vorbereitung fuer beta-test

### ISSUE THREAD

**Issue by bittorf** [weimarnetz/weimarnetz#51]
- [x] /tmp/NETPARAM erweitern: $WIFI_DEVS = /etc/init.d/S41build_static_netparam uebernehmen
- [x] kalua_init: neue variable: LOWMEM (wenn gesetzt, dann <32mb RAM)
- [x] kalua_init: bool_true() - ist praktisch zum sauberen abfragen von UCI-variablen
- [x] kalua: init: $IPT -> iptables --wait
- [x] kalua_init: am besten komplett uebernehmen
- [x] netfilter: redirect von ge-splashten usern auf das richtige interface: zeile 1190 + 1148
- [x] registrator-client fixen (JSON-parsing) + uebernehmen
- [ ] netfilter: bereinigen von allen "if CONFIG_PROFILE xy"
- [x] apply_profile: was muss alles nach einem update da/weg sein, damit es nicht kracht? (S140!)
- [x] ipsystem uebernehmen, wegen VPN-bereich aenderung
- [x] ipsystem-funktion: _ipsystem_getvar() - sehr praktisch
- [x] olsrd-ipv6 ausschalten: in apply_profile: /etc/init.d/olsrd6 disable

**Comment by glycoknob** [comment]
kurzes update: 

1:1 von kalua übernommen: 

    S41build_static_netparam 
    kalua_init
    registrator-client
    ipsystem

und ein paar kleinigkeiten, die angebracht erschienen.. z.b. math, neigh, ...
https://github.com/glycoknob/weimarnetz/commit/e61dda7193272909b8aa4e7f36ecb77e438338ea

alles was nicht benötigt wurde dann wieder gelöscht: 
https://github.com/glycoknob/weimarnetz/commit/cdcd1f0c033a29a7aa39eb744ef847230e83cc02

jetzt erstmal testen...

**Comment by glycoknob** [comment]
- [ ] cyassl rauswerfen, dafür polarssl nehmen..
    - [ ] apply_profile.code anpassen (check für cyassl) 
    - [ ] px5g-standalone durch px5g ersetzen 
    - [ ] .config überall anpassen 
  
- [ ] ipsystem - interface <-> subnetz klären
    - [ ] adhoc-interfaces in je eigenes /32 netz ???
    - [ ] 2.4+5ghz... br-wlan oder 10.64.x subnetz 
    - [ ] /etc/config/dhcp + NETPARAMS anpassen für 5ghz+adhoc ip-netz

- [ ] splash 
    - [ ] paket-abhängigkeiten für luci-weimar-splash richtig setzen (luci-freifunk..etc.pp) 
    - [ ] splash ohne luci? vielleicht später... 
    - [ ] splash auf eigenen port (macht alles einfacher!?) ..später? 

- [ ] vpn 
    - [ ] olsr nameservice dafür nutzen... 
    - [x] startup script für vpn 
    - [ ] netifd für ip adressen und routen verwenden (siehe kalua)
    - [ ] udp vs. tcp mal testen... siehe: http://sites.inka.de/bigred/devel/tcp-tcp.html 

nice to have: 

- [ ] squashfs blocksize 1024 scheint cool zu sein und spart einige kb 
- [ ] kein usb für 4mb geräte die keinen port haben (841ND) - spart auch ein paar kb
- [ ] tc für olsrd/wmm 
- [ ] 3.14 kernel

**Comment by andibraeu** [comment]
den tausch der ssl-lib würd ich auf später verschieben. im Moment kommen wir mit cyassl aus (und aus luci besteht noch eine nicht aufgelöste Abhängigkeit zu libcyassl)

außerdem:
libcyassl_3.2.0-1_ar71xx.ipk                       24-Sep-2014 09:29               70865
libpolarssl_1.3.9-2_ar71xx.ipk                     20-Jan-2015 13:48              140001

**Comment by andibraeu** [comment]
zur Splashpage: die hab ich extra auf lua und luci aufgebaut, weil das vorherige Zusammenbauen der HTML-Datei nicht zuverlässig geklappt hat.

Ziel für mich war auch explizit, diese Seite in die Luci-Oberfläche zu integrieren und auch zu anderen Zeitpunkten aufrufbar zu machen.

**Comment by glycoknob** [comment]
@andibraeu: klingt gut... hab ich nicht gewusst. dann erstmal so. 

ich konnte jetzt auch ohne cyassl bauen. wichtig ist ja nur, dass nicht 2 ssl libs im image sind. px5g-standalone nutzt leider auch polarssl. aber in der größe sollte das dennoch kleiner als polarssl + dagegen linken sein.

**Comment by glycoknob** [comment]
Uralt und längst gelöst :)
