### ISSUE TITLE
VPN Update-Pfad ist kaputt

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#56]
Sorry für den Spam... 

versuch grad das VPN zum laufen zu bekommen und `/etc/config/system` auf meinen Router sieht so aus: 

```
config vpn 'vpn'
        option domain 'weimarnetz.de'
        option prefix 'vpn'
        option jsonpath '/freifunk/vpn/'
        option proto 'olsr'
        option enable '1'
        option ipaddr 'vpn.weimarnetz.de'

```

Der Präfix hat sich jetzt ja auf `v` verändert und das ist auch korrekt in `apply_profile.code` nur... 

ist `keepsettings=1` für `/etc/config/system` und `ffweimar` Profil aktiviert... das wird bei `sysupgrade` ohne -n gar nicht geupdated... 

Wenn ich es auf keepseetings=0 stelle und nochmal `apply_profile.code` durchlaufen lasse.. passt es dann... 

hängt vielleicht mit 

- [ ] apply_profile: was muss alles nach einem update da/weg sein, damit es nicht kracht? (S140!)

aus #51 zusammen.

**Comment by bittorf** [comment]
ok, gefixt.
