### ISSUE TITLE
VPN-Script ist kaputt...

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#67]
Fazit vom heutigen debuggen... 

vermutlich Backports nach Barrier Breaker, die `jshn` Änderungen mit sich bringen... 

siehe auch: https://dev.openwrt.org/ticket/18464

konkret `_vpn build_vars` hier: https://github.com/weimarnetz/weimarnetz/blob/master/openwrt-addons/etc/kalua/vpn#L253

**Comment by bittorf** [comment]
ungefaehr so muss es aussehen, siehe registrator-script:
{{{
json_load "$HTTP_ANSWER"
json_get_var 'JSON_VAR_status' 'status'
json_get_var 'JSON_VAR_message' 'message'
}}}

**Comment by glycoknob** [comment]
Sollte jetzt laufen.
