### ISSUE TITLE
Speicherplatz sparen

### ISSUE THREAD

**Issue by L337hium** [weimarnetz/weimarnetz#77]
folgende aenderungen im 'menuconfig' sparen bis zu 200KB (fuer 4MB Router)

Utilities --> discs --> swap-utils = n

Base System --> busybox --> Linux System Utils --> swponoff = y

Kernel modules --> Wireless Drivers --> kmod-mac80211 --> Enable 802.11s mesh support = n 

Kernel modules --> USB Support --> kmod-usb2 / kmod-usb-core / kmod-usb-ohci = n

Global build settings --> Crash logging / Enable support for printk / Enable process core dump support / Enable printk timestamps = n

Base System --> busybox --> Linux System Utils --> dmesg = n

Target Images --> squashfs --> (1024) Block size (in KiB)

Optional `opkg` rausoperieren

**Comment by L337hium** [comment]
Also fuer einen **TP-Link 841ND v8** wir sind von 36?? KB, auf 34?? KB und jetzt auf **3268 KB** runter!

3840    bin/ar71xx/openwrt-r44620-ar71xx-generic-tl-wr841n-v8-squashfs-factory.bin
3268    bin/ar71xx/openwrt-r44620-ar71xx-generic-tl-wr841n-v8-squashfs-sysupgrade.bin

**Comment by L337hium** [comment]
Die alte Firmware mit r37711 hat 3539 KB.

**Comment by andibraeu** [comment]
> Optional opkg rausoperieren
> 

opkg sollte nicht raus, ist schließlich das Standardpaketmanagement für
OpenWrt. Und unsere Softwareerweiterungen kommen ja inzwischen aus als
Paket.
Da würden wir uns also Updates ziemlich verbauen

**Comment by storchi** [comment]
bittorf meinte, man könnte nen alias auf opkg scripten, dass dann ansagt wo man sich mit wget das opkg binary ziehen kann und unter /bla/xxx ablegt.

**Comment by bittorf** [comment]
ja, bin gerade am basteln:
# build: noOPKG ->
cd /tmp
  wget http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/base/opkg_9c97d5ecd795709c8584e972bfdf3aee3a5b846d-7_ar71xx.ipk
  tar xzf opkg_*
  rm ./debian-binary ./control.tar.gz ./opkg_*
  tar xvzf data.tar.gz ./bin/opkg
  rm data.tar.gz
  /tmp/bin/opkg install mein_packet
  rm /tmp/bin/opkg

das spart nochmal 50k

**Comment by bittorf** [comment]
wireless-tools = 'iwconfig' aus 'base-system' kann auch weg. spart nochmal ***50k***

**Comment by bittorf** [comment]
und 'px5g' braucht man auch nicht (initialer zertifikats-generator fuer https) - den brauchen nur ganz frische knoten, die noch keins haben (wird bei sysupgrade uebernommen)

**Comment by bittorf** [comment]
und JFFS2 kann gehackt werden, das man noch 2 bloecke mehr frei hat (128k)

**Comment by glycoknob** [comment]
weiß nicht ob es sich für 50kb lohnt opkg rauszuoperieren... opkg für Updates ist schon ganz nett.

**Comment by bittorf** [comment]
aber 'opkg' geht doch weiterhin - es wird halt nur "kurz, mal eben" aus dem internet runtergeladen und in die ram-disk kopiert...

**Comment by bittorf** [comment]
falls es noch fragen gibt 8-)
bastian@gcc20:~$ id bastian
uid=1337(bastian) gid=1337(bastian) groups=1337(bastian)

**Comment by bittorf** [comment]
utilities 'iwinfo' und 'px5g' also auch weg...

**Comment by bittorf** [comment]
px5g muesste also auch wenn es gebraucht wird aus dem netz geladen -> in die ramdisk -> cert machen und bin wegwerfen...

**Comment by bittorf** [comment]
image ist jetzt 3140k und da ist luci UND tc schon drinne...

**Comment by bittorf** [comment]
mit dem 'opkg', sieht jetzt so aus:

root@EG-labor-AP:~ $OPKG info kernel
Mar 25 11:57:22 ' [up 27706s 7430144 bytes free] TERM:screen -ash [daemon.info] opkg_raminstaller() fetching filename from http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/base
Connecting to downloads.openwrt.org (78.24.191.177:80)
Connecting to downloads.openwrt.org (78.24.191.177:80)
-                    100% |**********************************************************************************************|   132k  0:00:00 ETA
Mar 25 11:57:24 ' [up 27708s 7393280 bytes free] TERM:screen -ash [daemon.info] opkg_raminstaller() fetching package from http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/packages/base/opkg_9c97d5ecd795709c8584e972bfdf3aee3a5b846d-7_ar71xx.ipk
Connecting to downloads.openwrt.org (78.24.191.177:80)
opkg.ipk             100% |**********************************************************************************************| 51512   0:00:00 ETA
./bin/opkg
Package: kernel
Version: 3.18.9-1-628cca0666bd03e08db24f81b10bb80c
Depends: libc
Status: install hold installed
Architecture: ar71xx
Installed-Time: 1427091548

root@EG-labor-AP:~ $OPKG info kernel
Package: kernel
Version: 3.18.9-1-628cca0666bd03e08db24f81b10bb80c
Depends: libc
Status: install hold installed
Architecture: ar71xx
Installed-Time: 1427091548

**Comment by bittorf** [comment]
alles eingepflegt, bei bedarf kann man nochmal in der liste schmöckern

**Comment by andibraeu** [comment]
es fehlt noch das Script, um px5g temporär zu laden.

**Comment by bittorf** [comment]
ich habe probiert px5g rauszunehmen, aber das braucht nur 9k - ist also den aufwand nicht wert. bei 50k fuer opkg schon eher...

**Comment by bittorf** [comment]
wer list hat kann den autodownload fuer opkg machen:
https://github.com/bittorf/kalua/blob/master/openwrt-addons/etc/kalua/software#L464

zusaetzlich muss im loader noch gesetzt sein:
OPKG="_software opkg_raminstaller"
und alle aufrufe von opkg muessen ersetzt werden durch $OPKG
(wobei das im normalfall OPKG=/bin/opkg ist....
