### ISSUE TITLE
Menu und Splash auf Mobilen Geräten vertragen sich nicht...

### ISSUE THREAD

**Issue by glycoknob** [weimarnetz/weimarnetz#80]
![screenshot_2015-04-26-03-53-59](https://cloud.githubusercontent.com/assets/187041/7335541/556aadc0-ebc8-11e4-91a0-15c9785f82d0.png)

**Comment by L337hium** [comment]
das geraet in der breitbildansicht verwenden hilft *raeusper* -- na wenn wer bootstrap beherscht koennte man das mal fixen, abernaja...

**Comment by andibraeu** [comment]
*raeusper* http://getbootstrap.com/2.3.2/

**Comment by glycoknob** [comment]
So ein Hamburger ☰ wäre cool für das Menü auf mobilen Geräten.. das geht wohl erst ab Bootstrap3.x..

Hab grad hier entdeckt: https://developer.chrome.com/devtools/docs/device-mode damit müsste man das schnell fixen können... bootstrap lernen ist nicht viel aufwand, ist nur css und html.

**Comment by glycoknob** [comment]
Hat sich erledigt.. ist schon im aktuellen luci-gefixt: https://github.com/openwrt/luci/pull/333 

Man muss aber den Cache löschen damit es neu angezeigt wird, kann man vielleicht über Header lösen.
